src/components/AccountDetails.js, src/containers/AccountDetails.js, src/util/db.js
=> Subtler delete text.

src/components/AccountList.js, src/components/AccountListRow.js, src/containers/AccountList.js
Closes #34 
Also adds an intro text to create a new account if you have none.
=> Round icons on the list

src/components/App.js, src/components/IconChooser.js, src/containers/AccountList.js, src/containers/AccountNew.js, src/containers/IconChooser.js
=> Selecting account icon

package.json, src/containers/AccountNew.js, src/styles/index.js
=> Backup recovery phrase.

README.md, setup_macos.sh, src/components/AccountListRow.js
fixed displaying AccountListRow icon on iOS, updated setup_macos.sh and README.md with rustup instructions
=> osx and ios fixes

src/reducers/accounts.js
=> Fixing pin for new accounts.

src/components/QrScanner.js, src/containers/QrScanner.js, src/reducers/routes.js
Most probably solves #50 
Also it works way faster for me over all, but switching to "Scan Transaction QR" tab takes just a little bit longer.
=> Disable Camera when the screen is not active.

src/containers/AccountPin.js, src/reducers/scanner.js
=> Dismiss keyboard on terminal PIN screens.

.travis.yml, package-lock.json, package.json, rust/signer/Cargo.lock, rust/signer/Cargo.toml
the actual fix and tests are in blockies repo, https://github.com/debris/blockies.rs/commit/ec4b49f86cfa121469ee28f2acf3b057f5777a05
=> fixed broken identicons

ios/NativeSigner/Info.plist
https://github.com/paritytech/parity-signer/issues/83
=> Removed unused permissions on iOS

README.md
=> updated README.md requirements

src/screens/Security.js
I spoted a typo "Secure devices do no the sensors" :)
=> Typo and simplification

docs/privacy-policy.md.js, docs/terms-and-conditions.md.js, ios/NativeSigner.xcodeproj/project.pbxproj, ios/NativeSigner/Info.plist, package.json, src/App.js, src/components/Markdown.js, src/screens/About.js, src/screens/Loading.js, src/screens/PrivacyPolicy.js, src/screens/TermsAndConditions.js, src/util/db.js, yarn.lock
=> TermsAndConditions and PrivacyPolicy screens added

rust/signer/Cargo.lock, rust/signer/Cargo.toml, rust/signer/src/lib.rs
* Updated all dependencies to latest versions, fixed what I could.
* Tests that depend on `jni` feature don't compile yet, the simple RLP test is passing.
* Need to test integration with JS code.
=> [WIP] Make Rust Compile Again

android/app/build.gradle, ios/NativeSigner.xcodeproj/project.pbxproj, rust/signer/Makefile, src/util/native.js
~~NOTE:~~
~~TODO: recompile the iOS binary in order to not trim the first byte of the address~~
=> Double 0x fix in address

src/screens/AccountPin.js, src/screens/AccountUnlock.js, src/stores/AccountsStore.js, src/stores/ScannerStore.js
- self explanatory, taken out of the other PR :)
=> Removed unused components, variables and functions

README.md, package.json
It's failing and "has never worked"
=> Replace failing "yarn run cli.." by "react-native.."

src/components/AccountSeed.js
closes https://github.com/paritytech/parity-signer/issues/145
=> Do not capitalize recovery phrase words

src/screens/AccountNew.js
=> Additional account validation added

src/App.js, src/screens/AccountUnlock.js, src/screens/MessageDetails.js, src/screens/QrScanner.js, src/screens/SignedMessage.js, src/stores/AccountsStore.js, src/stores/ScannerStore.js, src/util/message.js
=> Ethereum message sign

README.md
Closes #193.
Closes #208.
CC: #216.
=> README: Add info on Android Studio and Troubleshooting

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json
=> Bump app version to 2.2

ios/NativeSigner.xcodeproj/project.pbxproj, src/screens/AccountRecover.js
- fix part of https://github.com/paritytech/parity-signer/issues/261
=> Keyboard should not block TextInput

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json, src/screens/About.js
- use semver
- bump to 2.2.1
- show the version in the "About"
=> Bump to 2.2.1

package.json, src/screens/AccountNew.js, src/screens/AccountRecover.js, yarn.lock
removes the RN KeyboardAvoidingView in favor of KeyboardAwareScrollView #268
=> fix: padding when keyboard is visible

package.json, src/components/AccountCard.js, src/components/AccountDetailsCard.js, src/components/AccountIconChooser.js, src/components/NetworkButton.js, src/constants.js, src/screens/AccountNetworkChooser.js, src/screens/AccountNew.js, src/screens/AccountRecover.js, src/stores/ScannerStore.js, src/util/account.js, yarn.lock
#252 
* refactor constants.js.
* add Substrate endpoint in constants.js
* add lodash as a dependency.
* create NetworkButton Component.
=> fix: refactor the network list and add lodash

src/components/AccountCard.js, src/components/AccountDetailsCard.js, src/screens/AccountBackup.js, src/screens/AccountDetails.js, src/screens/AccountEdit.js, src/screens/AccountList.js, src/screens/AccountNetworkChooser.js, src/screens/AccountNew.js, src/screens/AccountRecover.js, src/screens/MessageDetails.js, src/screens/SignedTx.js, src/screens/TxDetails.js, src/stores/AccountsStore.js, src/stores/ScannerStore.js, src/util/account.js, src/util/db.js, src/util/transaction.js
follow up of #275 
rename the `chainId` to `networkKey` in most case, other place use `ethreumChainId`
=> fix: rename chainId

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json
=> chore(): bump to 3.0.0

package.json, yarn.lock
=> chore: bump version of prettier

README.md
=> fix: update readme with yarn start command

src/constants.js, src/util/decoders.spec.js
=> Add Genesis Hash

src/constants.js, src/util/suri.js
genesis hash from branch `v0.5.1`
running `polkadot --dev` commit e086465916c2778a7dede7dc62e551d801dc12ca
=> Add genesis hash from polkadot --dev v0.5.1

src/screens/SignedTx.js, src/stores/AccountsStore.js, src/stores/ScannerStore.js, src/util/account.js
closes #360
| #360 problem case        | My Crypto Example           |  Kusama just to be sure |
| ------------- |:-------------:| -----:|
| ![ezgif-2-8c616876b4a4](https://user-images.githubusercontent.com/10432070/64461392-5b628f80-d0fd-11e9-9317-eecbae925a04.gif)     | ![ezgif-2-10b0f0de56fe](https://user-images.githubusercontent.com/10432070/64461553-d1ff8d00-d0fd-11e9-95e8-2c3e54c3e706.gif) | ![ezgif-2-6aed78ae0ae8](https://user-images.githubusercontent.com/10432070/64461652-0f641a80-d0fe-11e9-925e-b5762cdd4071.gif) |
=> fix: allow signing of accounts not on device

src/screens/AccountNetworkChooser.js, src/screens/AccountPin.js
close #374 .
Also clean one place in `AccountNetworkChooser.js` to make the code clear.
=> fix: add pin check

src/components/AccountCard.js, src/components/AccountIconChooser.js, src/components/Address.js, src/screens/AccountList.js
=> align height in Account new screen

src/screens/MessageDetails.js, src/screens/SignedMessage.js
=> fix: flexible message field

.gitlab-ci.yml
the test section of the `.gitlab-ci.yml` was previously commented out.
TODO
use this pull request to add custom commands that should be used for testing (replace current script).
=> test: pull requests draft

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json
=> chore: bump 401

e2e/identityManipulation.spec.js, e2e/testIDs.js, src/components/SecurityHeader.js, src/screens/AccountNetworkChooser.js, src/screens/LegacyAccountList.js, src/screens/PathsList.js
closes #486.
Now the scan button is moved to the top right bar of the application.
=> style: move scan button to top bar

README.md, package.json
=> docs: add debug unit test command into package.json

docs/terms-and-conditions.md.js
I was asked by Fraser to update to these new T&C. The website will be updated too.
=> chore: Update terms-and-conditions.md.js

src/screens/AccountDetails.js, src/screens/PathDetails.js
close #534 
please merge into master after #536 ,  #532
Self explained.
=> chore: add name into account qr code

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json
=> chore: bump version to 4.0.8

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json
=> chore: bump version to 4.1.0

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json
=> chore: bump version 4.1.1

android/app/src/main/java/io/parity/signer/EthkeyBridge.java
Fix android compilation errors.
=> fix: compilation error on android

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json
=> chore: bump version v4.2.0

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json
=> chore: bump version 4.2.1

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json, src/modules/sign/components/PayloadDetailsCard.tsx
fix parsing bugs on unrecognized network key
=> fix: parsing bug on unrecognized network key

src/utils/identitiesUtils.ts
closes #517 .
The new grouping order is :
For groups:
* Single path group comes first. 
* For groups with multiple paths, compare the ASCII code with their group title.
For paths inside group:
* if the last path fragment is number, and it is a small number, it comes first
* If the last path fragment is not a number, compare the ASCII code with thier last fragment.
like followings
=> fix: reorder the paths and pathsGroups

src/modules/main/components/NetworkSelector.tsx, test/e2e/specs/signing.spec.ts
=> fix: consistently use network root account as default created account

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json, src/components/AccountSeed.tsx
quick fix on seed input cursor bug
=> fix: seed input bugs

docs/tutorials/New-Network.md, src/constants/networkSpecs.ts, src/modules/sign/screens/QrScanner.tsx, src/modules/sign/screens/SignedTx.tsx, src/stores/ScannerContext.ts
=> chore: update dot naming

android/app/build.gradle, ios/NativeSigner/Info.plist, package.json
=> chore: bump to 4.5.2

android/app/build.gradle, android/build.gradle
This PR upgrade android compiling target sdk version.
=> build: upgrade andriod compling sdk version fix building error

package.json
Add commmand for building an iOS unsigned binary file.
=> build: add command for buiilding ios unsigned binary file

src/utils/regex.ts
=> fix: allow special characters in password

docs/terms-and-conditions.md.js
I adapted with the changes made by the legal team
=> chore: Sync EULA with new address

android/app/build.gradle, ios/NativeSigner.xcodeproj/project.pbxproj, ios/NativeSigner/Info.plist
=> docs: Bump versions

.gitlab-ci.yml, android/app/build.gradle, android/gradle.properties
Disable apk minification; this makes apk huge, but it probably works at least.
=> fix: rn build android

android/app/build.gradle, android/app/src/main/java/io/parity/signer/MainActivity.kt, android/app/src/main/java/io/parity/signer/components/Documents.kt, android/app/src/main/java/io/parity/signer/components/PP.kt, android/app/src/main/java/io/parity/signer/components/TAC.kt, android/app/src/main/java/io/parity/signer/screens/LandingView.kt
Just default material rendering. We can tweak it later, now it seems OK to me and is certainly better than before.
=> style: android: markdown for docs

docs/src/wiki/FAQ.md
To close #965 and similar future issues in the nicest way possible
=> docs: FAQ.md

android/app/src/main/java/io/parity/signer/screens/NewAddressScreen.kt, android/app/src/main/java/io/parity/signer/screens/RecoverSeedName.kt
fixes improper seed screening.
To reproduce on current master: try to derive key OR try to recover seed.
=> fix: android: fix seedname base64 in new address and recover seed

android/app/src/main/res/values/themes.xml
=> style: change status bar icons colors

android/app/build.gradle
This reverts commit 0dcc0bcde410a5bc42d6d3212689f1f3e36f0aec.
=> revert: "os specific paths to llvm prebuilt toolchain (#981)"

android/app/src/main/java/io/parity/signer/SignerScreen.kt, android/app/src/main/java/io/parity/signer/models/Camera.kt, android/app/src/main/java/io/parity/signer/screens/ScanScreen.kt
"Start over" button has to work.
=> fix: android: start over has to reset scanning

android/app/src/main/java/io/parity/signer/screens/ScanScreen.kt
=> fix: android: scan screen always on

rust/db_handling/src/helpers.rs, rust/db_handling/src/interface_signer.rs, rust/db_handling/src/tests.rs, rust/defaults/src/lib.rs, rust/definitions/src/history.rs, rust/definitions/src/keyring.rs, rust/definitions/src/test_all_errors_signer.rs, rust/transaction_parsing/src/add_specs.rs, rust/transaction_parsing/src/holds.rs, rust/transaction_parsing/src/load_metadata.rs, rust/transaction_parsing/src/test_all_cards.rs, rust/transaction_signing/src/tests.rs
=> fix: backend: verifier key hash type

.github/workflows/rust-test-android.yml
This test is failed by certain modifications in #1092 and I nearly forgot about it; thus this should be automated.
Maybe this should be done in parallel, maybe on both platforms.
=> ci: rust test all features

android/app/build.gradle, android/build.gradle
mozilla/rust-android-gradle#91 was fixed, let's give it a try
=> fix: paths to ndk were fixed in upstream

docs/src/development/UOS.md
Change markdown flavor from github to mbook
=> docs: unescape xor

android/app/src/main/java/io/parity/signer/modals/SeedBackup.kt, ios/NativeSigner/Modals/Backup.swift
Keep screen active on backup view
Fixes #1107
=> chore: keep screen active on backup view

.github/workflows/actions.yml
An attempt to fix iOS builds in CI.
=> fix: build on ios

README.md
Tested Android build on Mac. Works fine, although one minor fix is required.
=> docs: android build on mac

android/app/src/main/java/io/parity/signer/components/HistoryCard.kt, android/app/src/main/java/io/parity/signer/components/HistoryCardExtended.kt, ios/NativeSigner/Cards/HistoryCardExtended.swift, ios/NativeSigner/Components/HistoryCard.swift, rust/db_handling/src/identities.rs, rust/db_handling/tests/tests.rs, rust/definitions/src/history.rs, rust/signer/src/signer.udl
Add logging on seed removal event
<details>
<summary>Android screenshot</summary>
</details>
<details>
<summary>iOS screenshot</summary>
</details>
Fixes #1020
=> chore: log seed removal

docs/src/development/UOS.md
Docs are no longer [there](https://github.com/paritytech/parity-signer/runs/7461343019?check_suite_focus=true)
=> fix: point docs to docs.rs

rust/Cargo.lock
=> chore: bump chrono

.github/workflows/actions.yml, .github/workflows/android-app.yml, .github/workflows/docs.yml, .github/workflows/rust-clippy.yml, .github/workflows/rust-test-android.yml, .github/workflows/rust-test-ios.yml
To fix Rust Cache step on GAs
Did a test run here, seems to save cache properly: https://github.com/paritytech/parity-signer/actions/runs/2831246280
=> ci: update Rust Cache step in all GA actions

rust/definitions/src/crypto.rs, rust/definitions/src/history.rs, rust/definitions/src/keyring.rs, rust/definitions/src/metadata.rs, rust/definitions/src/navigation.rs, rust/definitions/src/network_specs.rs, rust/definitions/src/types.rs, rust/definitions/src/users.rs, rust/generate_message/src/error.rs, rust/navigator/src/actions.rs, rust/navigator/src/alerts.rs, rust/navigator/src/modals.rs, rust/parser/src/decoding_sci.rs, rust/parser/src/decoding_sci_ext.rs, rust/qr_reader_phone/src/lib.rs, rust/qr_reader_phone/src/process_payload.rs, rust/qrcode_rtx/src/lib.rs
Fix clippy on new rust stable.
=> chore: make clippy happy on new stable

pull_request_template.md
This PR introduces new PR template as requested by @montekki 
- add new single template to be used for PRs with optional sections
Maybe it's better to have separate templates and parametrise PRs with something like `ios`, `mobile`, `backend`, but I think just simple one with optional sections might be a better start point 🙏🏻
=> chore: introduce PR template

ios/NativeSigner.xcodeproj/project.pbxproj
This reverts commit 75666602339676fb165e6236f9d7b4ca6660ad79.
=> chore: Revert "chore: fix build issues and Preview Content"

rust/Cargo.lock, rust/qr_reader_phone/Cargo.toml, rust/qr_reader_phone/src/lib.rs, rust/qr_reader_phone/src/parser.rs
Improve QR payload parser
https://paritytech.github.io/parity-signer/development/UOS.html#qr-code-structure
- use [nom](https://github.com/Geal/nom)
- re-write `get_payload` function
I'd propose re-write parser in small chunks. One format - one PR
=> chore: improve QR payload parser

android/app/build.gradle, android/app/src/main/java/io/parity/signer/MainActivity.kt, android/app/src/main/java/io/parity/signer/screens/LandingView.kt, android/build.gradle
This PR bumps deps that need bumping.
=> chore: dependency bumps

android/app/build.gradle, android/build.gradle
=> fix: github action fix

README.md
=> docs: Updated readme instructions for android build.

.github/workflows/actions.yml, .github/workflows/testflight.yml, ios/NativeSigner.xcodeproj/project.pbxproj, ios/NativeSigner/Components/Modifiers/HiddenScrollContainerModifier.swift, ios/NativeSigner/Screens/KeyDetails/KeyDetailsView.swift, ios/NativeSigner/Screens/KeySetsList/KeySetList.swift
This PR fixes issue on iOS 16 with broken background color behind `List` item. Implementation has changed underneath and `List` no longer depends on `NSTableView`, hence we need to conditionally use new modifier for clearing background.
- dedicated `ViewModifier` that can be applied over `List` elements
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/190398024-eea86abd-c79e-4799-80af-715935b6e0bf.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/190398220-b06b3dac-84d8-4b78-9f86-edf1e80a5bae.png" width="320px">|
|<img src="https://user-images.githubusercontent.com/1955364/190398071-725d1683-d804-447c-9d14-cbdcaa58b1ae.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/190398261-4aeeea35-889a-40 …
=> style: fix iOS 16 background issue

.github/workflows/actions.yml, .github/workflows/android-app.yml, .github/workflows/docs.yml, .github/workflows/rust-clippy.yml, .github/workflows/rust-test-android.yml, .github/workflows/rust-test-ios.yml, .github/workflows/testflight.yml, README.md, rust/Cargo.lock, rust/signer/Cargo.toml
Bumps `uniffi` version to `0.20.0`.
=> chore: bump uniffi-rs

android/src/main/java/io/parity/signer/bottomsheets/PrivateKeyExportBottomSheet.kt, android/src/main/java/io/parity/signer/bottomsheets/SufficientCryptoReady.kt, android/src/main/java/io/parity/signer/bottomsheets/TypesInfo.kt, android/src/main/java/io/parity/signer/components/HistoryCardExtended.kt, android/src/main/java/io/parity/signer/components/IdentIcon.kt, android/src/main/java/io/parity/signer/components/KeyCardOld.kt, android/src/main/java/io/parity/signer/components/MetadataCard.kt, android/src/main/java/io/parity/signer/components/SeedCard.kt, android/src/main/java/io/parity/signer/components/transactionCards/TCAuthor.kt, android/src/main/java/io/parity/signer/components/transactionCards/TCAuthorPlain.kt, android/src/main/java/io/parity/signer/components/transactionCards/TCAuthorPublicKey.kt, android/src/main/java/io/parity/signer/components/transactionCards/TCID.kt, android/src/main/java/io/parity/signer/components/transactionCards/TCMeta.kt, android/src/main/java/io/parity/signer/components/transactionCards/TCTypesInfo.kt, android/src/main/java/io/parity/signer/components/transactionCards/TCVerifier.kt, android/src/main/java/io/parity/signer/components2/CircularCountDownTimer.kt, android/src/main/java/io/parity/signer/components2/KeyCard.kt, android/src/main/java/io/parity/signer/components2/base/CloseIcon.kt, android/src/main/java/io/parity/signer/screens/NetworkDetails.kt, android/src/main/java/io/parity/signer/screens/SettingsScreen.kt, android/src/main/java/io/parity/signer/screens/VerifierScreen.kt, android/src/main/java/io/parity/signer/ui/theme/Color.kt, android/src/main/java/io/parity/signer/ui/theme/Typeface.kt, android/src/main/res/values/strings.xml
Only ui changes
upd images for 26.09
=> chore: Updated key component 

rust/Cargo.lock, rust/generate_message/Cargo.toml, rust/generate_message/src/parser.rs
Bumps `clap` dependency to new major version `4.0`.
=> chore: bump clap

rust/qr_reader_phone/src/process_payload.rs
`raptorq` stores collected packets internally, there is no need
to keep the same data in signer.
=> fix: use internal raptorq frame storage

android/src/main/java/io/parity/signer/models/Camera.kt, ios/NativeSigner/Models/CameraService.swift, rust/Cargo.lock, rust/qr_reader_phone/Cargo.toml, rust/qr_reader_phone/src/lib.rs, rust/signer/src/lib.rs, rust/signer/src/signer.udl
Removes some leftovers of old ffi system that encoded things into `JSON`s.
=> fix: do not encode as json array

rust/Cargo.lock, rust/qr_reader_pc/src/lib.rs, rust/qr_reader_phone/Cargo.toml, rust/qr_reader_phone/src/error.rs, rust/qr_reader_phone/src/lib.rs, rust/qr_reader_phone/src/parser.rs, rust/qr_reader_phone/src/process_payload.rs, rust/signer/src/lib.rs
Bring qr parsing error handling in line with the rest of the codebase.
=> chore: typed errors in qr reader

rust/generate_message/src/specs.rs
Make tests pass without Enternet connection
- disable `mass_fetch` test
=> fix: disable online tests

ios/NativeSigner/Core/Adapters/BackendNavigationAdapter.swift, ios/NativeSigner/Core/Navigation/NavigationCoordinator.swift, ios/NativeSigner/Resources/en.lproj/Localizable.strings, ios/NativeSignerTests/Core/Navigation/NavigationCoordinatorTests.swift
Simple error for debug / better UX for intermediate builds, to know what went wrong if it goes wrong
Btw, typo `futher` visible in screenshot is fixed 🙏🏻 
| Example error |
|-|
|<img src="https://user-images.githubusercontent.com/1955364/195344477-6b594c1f-689f-48f9-b6c2-5f58694a66b6.png" width="320px">|
=> feat: ios: error on Rust navigation errors

ios/NativeSigner/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift, ios/NativeSigner/Screens/KeySetsList/KeySetList.swift, ios/NativeSigner/Screens/ScreenSelector.swift
Fixing navigation issue from .newSeed to .keys
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/199085069-b75e54e3-9528-4cca-ba8c-2d56560eae3f.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/199085089-702905dc-ca54-456b-968d-7893708520d4.gif" width="320px">|
=> fix: ios: fix navigation from new seed to .keys

android/src/main/java/io/parity/signer/MainActivity.kt, android/src/main/java/io/parity/signer/SignerApp.kt
Application is created before main activity  (that in theory may be not created at all if background task)
moved init logging
=> feat: init logging in application creation

android/src/main/java/io/parity/signer/components/base/Checkbox.kt, android/src/main/java/io/parity/signer/components/base/CloseIcon.kt, android/src/main/java/io/parity/signer/components/items/KeyDerivedItemMultiselect.kt, android/src/main/java/io/parity/signer/components/items/KeySetItemMultiselect.kt, android/src/main/res/drawable/circle_checked_24.xml, android/src/main/res/drawable/circle_unckecked_24.xml, android/src/main/res/values/strings.xml
Created iOS/like checkbox as per design
=> feat: android made circle checkbox as per design

android/src/main/java/io/parity/signer/screens/scan/CameraExtras.kt, android/src/main/java/io/parity/signer/screens/scan/CameraView.kt, android/src/main/java/io/parity/signer/screens/scan/ScanProgressBar.kt, android/src/main/java/io/parity/signer/screens/scan/ScanScreen.kt, android/src/main/java/io/parity/signer/ui/theme/Color.kt
Improvement on qr code scanning
I've tested it and it's already better than in old implementation. I still think it should work better, will create an issue for that.
=> fix: Android camera scan improvements

rust/navigator/src/navstate.rs
Migrate from Logs default to Seed selector screen default
=> feat: seed selector is a default screen according to new design

android/build.gradle, build.gradle
=> feat: updated android dependencies

rust/signer/src/lib.rs, rust/signer/src/signer.udl
made reusing existing logic with existing data structures for the same task
=> fix: expose networks reusing

rust/Cargo.lock, rust/parser/Cargo.toml
=> fix: remove jsonrpsee dep from subxt

.github/workflows/rust-clippy.yml, rust/Cargo.lock, rust/parser/Cargo.toml, rust/parser/src/tests.rs
Fixes from paritytech/subxt#784
=> fix: subxt fixed clippy warnings

ios/NativeSigner/Screens/DerivedKey/CreateDerivedKeyView.swift, ios/NativeSigner/Screens/DerivedKey/Subviews/CreateDerivedKeyConfirmationView.swift, ios/NativeSigner/Screens/DerivedKey/Subviews/DerivationPathNameView.swift
Usage of a root key on some network has to be allowed via creating an ampty
derivation in a certain network.
=> feat: allow empty derivations to expose root key on some network

android/src/main/java/io/parity/signer/models/SignerDataModel.kt, android/src/main/java/io/parity/signer/screens/LandingView.kt
Fix accept conditions theme
Fix clean start - init history after init navigation that rust using for init db
=> fix: Android clean start fix

rust/db_handling/src/identities.rs, rust/transaction_signing/src/tests.rs
Correctly remove the whole seed info.
=> fix: make sure to remove all seed info

rust/qr_reader_phone/src/process_payload.rs
=> fix: correctly count collected legacy frames

ios/NativeSigner/Cards/TransactionCardView.swift, ios/NativeSigner/Core/Camera/CameraVideoOutputDelegate.swift, ios/NativeSigner/Core/Camera/CaptureDeviceConfigurator.swift, ios/NativeSigner/Core/Database/DatabaseMediator.swift, ios/NativeSigner/Core/Keychain/KeychainAccessAdapter.swift, ios/NativeSigner/Core/Keychain/SeedsMediator.swift, ios/NativeSigner/Models/CameraService.swift, ios/NativeSigner/Models/Documents.swift, ios/NativeSigner/Models/RustNative.swift, ios/NativeSigner/Screens/Scan/TransactionPreview.swift, rust/Cargo.lock, rust/navigator/src/lib.rs, rust/navigator/src/navstate.rs, rust/qr_reader_phone/Cargo.toml, rust/qr_reader_phone/src/lib.rs, rust/qr_reader_phone/src/process_payload.rs, rust/signer/Cargo.toml, rust/signer/src/lib.rs, rust/transaction_parsing/src/message.rs, rust/transaction_parsing/src/parse_transaction.rs
Remove logging until we have a more structured approach.
=> fix: remove logs for the time being

ios/NativeSigner.xcodeproj/project.pbxproj, ios/NativeSigner/Design/Heights.swift, ios/NativeSigner/Design/Spacing.swift, ios/NativeSigner/Previews/PreviewData+Components.swift, ios/NativeSigner/Resources/en.lproj/Localizable.strings, ios/NativeSigner/Screens/Onboarding/Overview/PaginatedScrollView.swift, ios/NativeSigner/Screens/Settings/SettingsItem.swift, ios/NativeSigner/Screens/Settings/SettingsView.swift, ios/NativeSigner/Screens/Settings/Subviews/Backup/BackupSelectKeyView.swift, ios/NativeSigner/Screens/Settings/Subviews/Backup/SettingsBackupModal.swift
We should add ability to backup keys from Setting, without use of navigation
| Normal size iPhone 8 | iPod Touch |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/216253554-6c57836f-f545-4244-a299-91a3ab019b54.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/216253483-dc842d95-c1e3-421b-851a-74d1830398b4.gif" width="320px">|
=> feat: ios: backup keys from settings

rust/db_handling/Cargo.toml, rust/navigator/Cargo.toml, rust/transaction_signing/Cargo.toml
=> chore: enable zeroize std feature

ios/NativeSigner/Components/NavigationBarView.swift, ios/NativeSigner/Modals/Deprecated/NewSeedBackupModal.swift, ios/NativeSigner/Resources/Assets.xcassets/common_icons/plus.imageset/Contents.json, ios/NativeSigner/Resources/Assets.xcassets/common_icons/plus.imageset/plux.svg, ios/NativeSigner/Screens/Containers/AuthenticatedScreenContainer.swift, ios/NativeSigner/Screens/DerivedKey/CreateDerivedKeyView.swift, ios/NativeSigner/Screens/DerivedKey/Subviews/DerivationPathNameView.swift, ios/NativeSigner/Screens/KeyDetails/Views/KeyDetailsView.swift, ios/NativeSigner/Screens/KeySetsList/KeySetList.swift, ios/NativeSigner/Screens/Logs/Views/LogsListView.swift, ios/NativeSigner/Screens/NewSeedScreen.swift, ios/NativeSigner/Screens/PublicKey/KeyDetailsPublicKeyView.swift, ios/NativeSigner/Screens/Scan/TransactionDetailsView.swift, ios/NativeSigner/Screens/Scan/TransactionPreview.swift, ios/NativeSigner/Screens/Settings/SettingsView.swift, ios/NativeSigner/Screens/Settings/Subviews/Backup/BackupSelectKeyView.swift, ios/NativeSigner/Screens/Settings/Subviews/Networks/NetworkSelectionSettings.swift, ios/NativeSigner/Screens/Settings/Subviews/Networks/NetworkSettingsDetails.swift, ios/NativeSigner/Screens/Settings/Subviews/PrivacyPolicyView.swift, ios/NativeSigner/Screens/Settings/Subviews/TermsOfServiceView.swift, ios/NativeSigner/Screens/Settings/Subviews/VerfierCertificateView.swift
Redesign for Key Details + required refactor to NavigationBarView to accommodate for multiple icons and make code more DRY 
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/216374547-be406c73-52ba-4b9b-9452-977eb90e925f.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/216374546-a0a723ae-23b0-4307-88df-124dab1b0e1e.gif" width="320px">|
=> style: ios: redesign for Key Details + refactor to NavigationBarView and 

ios/NativeSigner/Previews/PreviewData+Rust.swift, ios/NativeSignerTests/Screens/KeySetList/KeySetListViewModelBuilderTests.swift, rust/db_handling/src/interface_signer.rs, rust/db_handling/tests/tests.rs, rust/definitions/src/keyring.rs, rust/definitions/src/navigation.rs, rust/navigator/src/tests.rs, rust/signer/src/signer.udl
Allow to show network icons for each seed.
=> feat: seed used in network

ios/NativeSigner/Extensions/Localizable+Formatted.swift, ios/NativeSigner/Modals/Errors/ErrorBottomModal.swift, ios/NativeSigner/Modals/Errors/ErrorBottomModalViewModel.swift, ios/NativeSigner/Resources/en.lproj/Localizable.strings, ios/NativeSigner/Screens/CreateKey/CreateKeySetSeedPhraseView.swift
Updated copy, title style and added new modal with BS explanation for Create Key Set flow
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/218425782-c6f51769-1054-4db6-ae2e-98e8909a664a.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/218425803-5f47d985-d55e-49a5-9c05-9a32c6641ee1.gif" width="320px">|
=> feat: ios: create seed update

ios/NativeSigner/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift, ios/NativeSigner/Screens/KeyDetails/Views/KeyDetailsView.swift
This PR fixes the issue where backup modal requests pincode several times
=> fix: ios: fix issue where backup modal requests pincode several times

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Models/SharedDataModel.swift, ios/PolkadotVault/Screens/Settings/SettingsView.swift
Update "Wipe" functionality - skip onboarding, end up on Key Sets screen immediately (after passcode confirmation)
=> feat: ios: don't bring back onboarding on wipe all action

ios/PolkadotVault/Info.plist
Updates **only** visible name to Vault
=> chore: ios: update visible name for app to Vault

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Components/QRCode/AnimatedQRCodeView.swift, ios/PolkadotVault/Core/QRCode/QRCodeImageGenerator.swift, ios/PolkadotVault/Design/Spacing.swift, ios/PolkadotVault/Modals/ExportPrivateKey/ExportPrivateKeyModal.swift, ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift, ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetailsView.swift, ios/PolkadotVault/Screens/Onboarding/Airgap/AirgapMediator.swift, ios/PolkadotVault/Screens/Onboarding/Airgap/AirgapMediatorAssembler.swift, ios/PolkadotVault/Screens/Onboarding/Airgap/OnboardingAirgapView.swift, ios/PolkadotVault/Screens/Onboarding/OnboardingScreenshotsView.swift, ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift
Couple of bug fixes listed in commit messages for RC build
- ability to mock connectivity during onboarding
- add ability to have different style for private key qr code
- scroll view and same size QR code on Public key screen
- improvements for Screenshot screen
- visual improvements for key details title
- fix backup modal presentation on iOS 15
=> fix: ios: prerelease bug fixes

ios/PolkadotVault/Cards/AddressCard.swift, ios/PolkadotVault/Components/Buttons/NavbarActionButton.swift, ios/PolkadotVault/Components/Extensions/Text+Markdown.swift, ios/PolkadotVault/Components/NavigationBarView.swift, ios/PolkadotVault/Models/Documents.swift, ios/PolkadotVault/Resources/en.lproj/Localizable.strings, ios/PolkadotVault/Screens/SelectSeedForBackup.swift
Clean up PR to remove unused copy from `Localizable.strings` resources
=> chore: ios: cleanup unused copy

ios/PolkadotVault/Resources/en.lproj/Localizable.strings, ios/PolkadotVault/Screens/Onboarding/Airgap/OnboardingAirgapView.swift
Updates copy based on internal review
=> chore: ios: updated copy according to internal review

android/src/main/java/io/parity/signer/domain/SharedViewModel.kt
hide create new bottom sheet while no keys created
workaround while #1618 is not merged
=> fix: android: workaround while #1618 is not merged

android/src/main/java/io/parity/signer/components/base/Buttons.kt, android/src/main/java/io/parity/signer/domain/SharedViewModel.kt, android/src/main/java/io/parity/signer/domain/storage/SeedStorage.kt, android/src/main/java/io/parity/signer/screens/keysets/KeySetsNavSubgraph.kt, android/src/main/java/io/parity/signer/screens/onboarding/eachstartchecks/EachStartSubgraphScreen.kt, android/src/main/java/io/parity/signer/screens/onboarding/eachstartchecks/EachStartViewModel.kt, android/src/main/java/io/parity/signer/screens/onboarding/eachstartchecks/airgap/AirgapScreen.kt, android/src/main/java/io/parity/signer/screens/settings/SettingsScreen.kt, android/src/main/java/io/parity/signer/screens/settings/SettingsWipeConfirmation.kt, android/src/main/java/io/parity/signer/ui/rustnavigationselectors/ScreenSelectorsNew.kt, android/src/main/res/values/strings.xml, build.gradle
Fixes
- fix: android airgap made scrollable #1677
- android build plugin updated
- wrote default validity explicitly, while it probably won't fix #1678 - 5 min should be right valie.
- feat: redesigned settings and implemented new UI for wipe conformation fixes #1681
- moved hack to hide bottom sheet to a view to hide it when this screen is reopened as well
- fix: show airgap screen only on clean start or if airgap is breached
|-|-|
| ![wipe_black](https://user-images.githubusercontent.com/11879032/222570489-61169b57-058f-47c9-a466-b7bb75a68441.png) |  ![wipe_white](https://user-images.githubusercontent.com/11879032/222570501-37320606-9a56-4812-b2d0-85be4bd24a0c.png)|
=> fix: Android fixes from last testing

ios/PolkadotVault/Resources/en.lproj/Localizable.strings
=> chore: ios: update metadata portal links

rust/generate_message/src/helpers.rs
=> fix: clippy

android/src/main/java/io/parity/signer/components/AlertComponent.kt
fixed android all alerts usages and  fixes #1695
This is because we don't use android theming properly...
=> fix: android all alerts usage and #1695

android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsMenu.kt, android/src/main/res/values/strings.xml
=> feat: update keyset details menu options as per modern figma 

rust/Cargo.lock, rust/db_handling/Cargo.toml, rust/definitions/Cargo.toml
Fix warning from `cargo`:
```
warning: the following packages contain code that will be rejected by a future version of Rust: svg v0.10.0
```
=> chore(deps): bump plot_icon from 0.2.0 to 0.3.0

ios/PolkadotVault/Backend/CreateDerivedKeyService.swift, ios/PolkadotVault/Cards/TransactionCards/TCCall.swift, ios/PolkadotVault/Cards/TransactionCards/TCEnumVariantName.swift, ios/PolkadotVault/Cards/TransactionCards/TCFieldName.swift, ios/PolkadotVault/Cards/TransactionCards/TCFieldNumber.swift, ios/PolkadotVault/Components/Animators/TapAndDelayDismissAnimator.swift, ios/PolkadotVault/Components/CircularProgressView.swift, ios/PolkadotVault/Modifiers/KeyboardAvoidance.swift, ios/PolkadotVault/Screens/Containers/AuthenticatedScreenContainer.swift, ios/PolkadotVault/Screens/CreateKey/NewKeySet/EnterKeySetNameView.swift, ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetNameView.swift, ios/PolkadotVault/Screens/CreateKey/WrappingHStack.swift, ios/PolkadotVault/Screens/DerivedKey/Subviews/DerivationPathNameView.swift, ios/PolkadotVault/Screens/KeySetsList/KeyListMoreMenuModal.swift, ios/PolkadotVault/Screens/Onboarding/Overview/OnboardingOverviewView.swift, ios/PolkadotVault/Screens/Onboarding/Overview/PaginatedScrollView.swift, ios/PolkadotVault/Screens/Scan/CameraView.swift, ios/PolkadotVault/Screens/Scan/Services/CameraService.swift, ios/PolkadotVault/Screens/Settings/Subviews/Backup/SettingsBackupModal.swift, ios/PolkadotVault/Screens/SignatureReady.swift
Update iOS codebase to newest SwiftFormat
`brew upgrade swiftformat` should work for anyone building locally
=> chore: ios: update formatting to newest SwiftFormat

android/src/main/java/io/parity/signer/screens/scan/camera/CameraCutout.kt, android/src/main/java/io/parity/signer/screens/scan/camera/ScanProgressBar.kt, android/src/main/java/io/parity/signer/screens/scan/camera/ScanScreen.kt
improve scan quality by moving frame more to the center
fixes  #1713
improving #1436
frame moved, text and scan progress paddings adjusted
Fixes
=> fix: android camera recognition improvements

android/src/main/java/io/parity/signer/screens/scan/camera/CameraCutout.kt
=> feat: android camera cutout increased according to feedback

android/build.gradle, android/src/main/java/io/parity/signer/components/sharedcomponents/CircularCountDownTimer.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsScreenFull.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/export/KeySetDetailsExportScreenFull.kt, android/src/main/java/io/parity/signer/screens/keysets/KeySetsNavSubgraph.kt, android/src/main/java/io/parity/signer/screens/keysets/create/NewKeySetBackupScreenFull.kt, android/src/main/java/io/parity/signer/screens/keysets/export/KeySetsExportScreenFull.kt, build.gradle
kotlin and compose and adjusted usages.
This hopefully will fix textfield issues on some devices
No UI/Logic changes
=> feat: android updated dependencies

android/src/main/java/io/parity/signer/screens/createderivation/DerivationCreateViewModel.kt
android excessive caching for networks list if fixed, after network updated it will appear now.
No UI changes
=> fix: android excessive caching for networks list

android/build.gradle
Will prepare release after input field bug fixed, probably tomorrow.
=> feat: updated app version to prepare release

android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsScreenView.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/export/KeySetDetailsMultiselectScreen.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/items/SeedKeyDetails.kt, android/src/main/java/io/parity/signer/screens/onboarding/eachstartchecks/airgap/AirgapScreen.kt, android/src/main/java/io/parity/signer/screens/settings/networks/list/NetworksList.kt
According to additional design review 
|-|-|
| ![image](https://user-images.githubusercontent.com/11879032/228526453-099648ac-39b4-4d9b-a2fc-d911689e53c4.png) | ![image](https://user-images.githubusercontent.com/11879032/228526591-334998c3-6d42-42cd-a298-8b7f55fb5e08.png) |
| ![image](https://user-images.githubusercontent.com/11879032/228528434-e8a630d9-a117-44bd-ac59-2d5287f2060f.png) |  |
=> fix: Android UI fixes 3

android/src/main/java/io/parity/signer/components/networkicon/NetworkIcon.kt, android/src/main/java/io/parity/signer/components/sharedcomponents/KeyCard.kt, android/src/main/java/io/parity/signer/screens/keydetails/KeyDetailsPublicKeyScreen.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/export/KeySetDetailsExportResultBottomSheet.kt
- Update key label element in public key screen
- Fixed network icons was not from preset in some screens
|-|-|
| ![image](https://user-images.githubusercontent.com/11879032/230398692-e1997430-db55-4526-b47f-b88db53bb685.png) | ![image](https://user-images.githubusercontent.com/11879032/230398804-af51f6a7-0482-4425-9693-4930d508dd28.png) |
=> feat: Android key component update

android/build.gradle
update version for hotfix release with scanning improved
=> feat: updated version for release

ios/PolkadotVault/Resources/en.lproj/Localizable.strings
Fixes: https://github.com/paritytech/parity-signer/issues/1788
=> fix: ios: fix metadata portal links in onboarding

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Backend/ExportPrivateKeyService.swift, ios/PolkadotVault/Components/QRCode/QRCodeAddressFooterView.swift, ios/PolkadotVault/Components/Text/NetworkIconCapsuleView.swift, ios/PolkadotVault/Design/PrimaryFont.swift, ios/PolkadotVault/Modals/ExportKeys/ExportMultipleKeysModal.swift, ios/PolkadotVault/Previews/PreviewData+Components.swift, ios/PolkadotVault/Resources/en.lproj/Localizable.strings, ios/PolkadotVault/Screens/DerivedKey/CreateDerivedKeyView.swift, ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift
This PR updates design for `Key Set Public Key` and for export private key as qr code footer is updated
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/233844563-d433cc70-19e7-421c-931a-9607f190fc5f.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/233844582-492528a6-a925-48e5-a14d-ad2dfa26afd4.gif" width="320px">|
=> feat: ios: Public Key design update

CODEOWNERS
=> chore: remove myself from CODEOWNERS

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Components/Errors/ConnectivityAlertOverlay.swift, ios/PolkadotVault/Components/Overlays/FullscreenModal.swift, ios/PolkadotVault/Screens/Containers/AuthenticatedScreenContainer.swift, ios/PolkadotVault/Screens/CreateKey/NewKeySet/CreateKeySetSeedPhraseView.swift, ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetSeedPhraseView.swift, ios/PolkadotVault/Screens/DerivedKey/CreateKeyNetworkSelectionView.swift, ios/PolkadotVault/Screens/DerivedKey/Subviews/AddKeySetUpNetworksStepOneView.swift, ios/PolkadotVault/Screens/DerivedKey/Subviews/AddKeySetUpNetworksStepTwoView.swift, ios/PolkadotVault/Screens/DerivedKey/Subviews/DerivationPathNameView.swift, ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetailsView.swift, ios/PolkadotVault/Screens/KeySetsList/KeySetList.swift, ios/PolkadotVault/Screens/Logs/Views/LogsListView.swift, ios/PolkadotVault/Screens/Onboarding/OnboardingAgreementsView.swift, ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift, ios/PolkadotVault/Screens/Scan/CameraView.swift, ios/PolkadotVault/Screens/Settings/SettingsView.swift, ios/PolkadotVault/Screens/Settings/Subviews/Backup/BackupSelectKeyView.swift, ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSelectionSettings.swift, ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSettingsDetails.swift, ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecsListView.swift, ios/PolkadotVault/Screens/Settings/Subviews/VerifierCertificate/VerifierCertificateView.swift
This PR fixes all found edge issues with Snackbar presentation in modal context after transitioning to native navigation
=> feat: ios: enable snackbar presentation in modal views

.github/workflows/android-app.yml, .github/workflows/android-release.yml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
new android gradle plugin and it's features, faster builds et.c.
no user facing changes
=> feat: Android agp update

ios/PolkadotVault/Screens/KeySetsList/KeySetList.swift
This PR aims to address issue: #1849
- fixed issues with passing data when navigating after native navigation refactor
- refactored code to move variables to ViewModel to align with other screens
=> fix: ios: #1849 - displayed key set can lead to details of another one

rust/definitions/src/helpers.rs
Root-Public key should be shown in UI as an SS58 with a prefix index of 1 (BareSr25519) or 3 (BareEd25519) - depending on crypto used.
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/7165377/6f12feec-e112-4e00-98c6-f1eb7f004b42" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/7165377/55a25abb-fbf3-49f4-a3ac-74dc01f405bd" width="320px">|
```bash
> subalfred key --network=substrate 0x4a755d99a3cbafc1918769c292848bc87bc2e3cb3e09c17856a1c7d0c784b41c
public-key 0x4a755d99a3cbafc1918769c292848bc87bc2e3cb3e09c17856a1c7d0c784b41c
substrate 5DkLGMQFPpTSA37BKo51DD1rznHNtU6rmhs2ZfYDFPJTzGHS
```
```bash
> subalfred key --network=BareSr25519 0x4a755d99a3cbafc1918769c292848bc87bc2e3cb3e09c17856a1c7d0c784b41c
public-key …
```
=> fix: #1871 display root address in BareSr25519 encoding

ios/PolkadotVault/Previews/Stubs+Signer.swift, ios/PolkadotVault/Stubs/Stubs+Signer.swift, rust/db_handling/src/interface_signer.rs, rust/db_handling/tests/tests.rs, rust/definitions/src/navigation.rs, rust/navigator/src/tests.rs, rust/signer/src/signer.udl
Pass derivation prefix from Rust
=> chore: add path_id to MMNetwork

.spellcheck/signer.dic, android/src/main/res/values/strings.xml, docs/src/development/UOS.md, docs/src/development/Vault-Structure.md, docs/src/tutorials/Add-New-Network.md, docs/src/tutorials/Hierarchical-Deterministic-Key-Derivation.md, docs/src/tutorials/Kusama-tutorial.md, docs/src/tutorials/Recover-Account-Polkadotjs.md
=> fix: typos

android/src/main/java/io/parity/signer/components/base/ScreenBaseComponents.kt, android/src/main/java/io/parity/signer/screens/createderivation/DerivationCreateViewModel.kt, android/src/main/java/io/parity/signer/screens/createderivation/derivationsubscreens/DerivationPathScreen.kt, android/src/main/java/io/parity/signer/screens/createderivation/derivationsubscreens/DeriveKeyNetworkSelectScreen.kt, android/src/main/java/io/parity/signer/screens/settings/networks/helper/HowAddNetworks.kt, android/src/main/java/io/parity/signer/screens/settings/networks/helper/HowUpdateMetadata.kt, android/src/main/res/values/strings.xml
refactored derivation path flow - no all networks and default path is different now
- no all networks option anymore
- default derivation path - path id or unused
|-|-|
| ![image](https://github.com/paritytech/parity-signer/assets/11879032/f358b8a0-ab50-40de-8799-4187295ea3d6) | ![image](https://github.com/paritytech/parity-signer/assets/11879032/12ec638c-617a-4113-97b1-17fb330f3cac) |
| ![image](https://github.com/paritytech/parity-signer/assets/11879032/3ca720a3-13a3-4a36-82cf-820311d4f604) |  |
=> feat: android create derivation upd

ios/PolkadotVault.xcodeproj/project.pbxproj
Just a version bump after last App Store release
=> chore: ios: version bump to 6.1.2

android/src/main/java/io/parity/signer/bottomsheets/PublicKeyBottomSheet.kt, android/src/main/java/io/parity/signer/components/sharedcomponents/KeyCard.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsNavSubgraph.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsScreenFull.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsScreenView.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/export/KeySetDetailsExportScreenFull.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/export/KeySetDetailsMultiselectScreen.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/items/SeedKeyDetails.kt, android/src/main/res/values/strings.xml
Show public key as bottom sheet
Public key as bottom sheet for key set details and key set export
|-|-|
| ![Screenshot_20230712_132711](https://github.com/paritytech/parity-signer/assets/11879032/c2fdce9f-3f0a-4b72-bb2a-2abdd5f3322c) | ![image](https://github.com/paritytech/parity-signer/assets/11879032/bf536ead-0602-4b04-be2e-409d8600463e) |
=> feat: Android pubkey sheet

rust/db_handling/src/identities.rs, rust/navigator/src/tests.rs
=> fix: clippy rust 1.71

build.gradle
For new android studio, improves android build
=> feat: update android gradle plugin

android/src/main/java/io/parity/signer/domain/FeatureFlags.kt, android/src/main/java/io/parity/signer/domain/RootUtils.kt
added feature toggle to test on emulator api 30 because emulator image is considered rooted
=> feat: android feature toggle to skip root check for development

android/src/main/java/io/parity/signer/components/networkicon/blockies/BlockiesIcon.kt, android/src/main/java/io/parity/signer/components/networkicon/jdenticon/Jdenticon.kt, android/src/main/java/io/parity/signer/ui/theme/Color.kt, android/src/main/java/io/parity/signer/ui/theme/Theme.kt
| 1 | 2 |
|-|-|
| ![image](https://github.com/paritytech/parity-signer/assets/11879032/969a4299-baba-40a9-8421-4cfbe83e2de9) | ![image](https://github.com/paritytech/parity-signer/assets/11879032/99ed7e2b-543a-4fa3-970e-ee4620e30a54) |
=> feat: fit square jdenticon into circle

android/build.gradle, android/src/main/java/io/parity/signer/screens/initial/explanation/OnboardingScreenFull.kt, build.gradle
updated android dependencies - gradle plugin, compose et.c. versions, target sdk
=> feat: Android agp upd

android/src/main/java/io/parity/signer/domain/Models.kt, android/src/main/java/io/parity/signer/screens/keydetails/KeyDetailsPublicKeyScreen.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/items/KeyDerivedItem.kt, android/src/main/java/io/parity/signer/screens/scan/importderivations/ImportDerivedKeysRepository.kt, android/src/main/java/io/parity/signer/screens/scan/transaction/dynamicderivations/AddDerivedKeysScreen.kt, android/src/main/res/values/strings.xml, ios/PolkadotVault/Backend/CreateDerivedKeyService.swift, ios/PolkadotVault/Screens/KeyDetails/Models/DerivedKeyRowModel.swift, ios/PolkadotVault/Screens/KeyDetails/Views/DerivedKeyRow.swift, ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift, ios/PolkadotVault/Stubs/Stubs+Signer.swift, rust/db_handling/src/identities.rs, rust/db_handling/src/interface_signer.rs, rust/db_handling/tests/tests.rs, rust/definitions/src/navigation.rs, rust/definitions/src/users.rs, rust/navigator/src/screens.rs, rust/navigator/src/tests.rs, rust/signer/src/lib.rs, rust/signer/src/signer.udl
Imported keys are just usual keys as discussed.
=> feat: remove imported keys - the are just keys

ios/PolkadotVault/Components/Image/IdenticonView.swift
Update all identicons types style to reflect newest designs
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/662a7128-4be4-4f90-a9b0-c3bf6a50cffb" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/fb537e20-e00b-4c17-b49d-268ea267421b" width="320px">|
=> feat: ios: update identicons style

rust/db_handling/src/helpers.rs, rust/db_handling/src/tests.rs, rust/signer/src/lib.rs, rust/signer/src/signer.udl
add `validate_seed_phrase` api
=> feat: add validate_seed_phrase api

ios/PolkadotVault/Components/Buttons/CircleButton.swift, ios/PolkadotVault/Components/Buttons/QRCodeButton.swift, ios/PolkadotVault/Screens/KeyDetails/Views/ManageKeySetsView.swift, ios/PolkadotVault/Screens/KeyDetails/Views/RootKeyDetailsModal.swift, ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift
Includes @tetekinandrey design review updates for redesigned flows
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/1c0c360b-9f8c-47e2-b674-220437fa7677" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/adcf3291-26ac-4ac8-9f6e-92db3e90c2a1" width="320px">|
=> chore: ios: design review updates after redesign

ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift
Fixes #2100 , as I forgot to move one piece of update logic to new handlers 
https://github.com/paritytech/parity-signer/assets/1955364/4d37b79d-6c92-4609-bf5b-c30dc44eb4d4
=> fix: ios: #2100 Address list is not updated after new network is added

ios/PolkadotVault/Resources/en.lproj/Localizable.strings, ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift
Minor design update for release build.
| Dark | Light |
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/cdd2acf6-5f14-4482-8c10-377528804c82" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/729e4a8e-3427-4eb6-b7a6-4502ca39c67e" width="320px">|
=> feat: ios: Remove title from Key Details screen

ios/PolkadotVault/Resources/en.lproj/Localizable.strings, ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecDetailsView.swift, ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecsListView.swift
Fixes #2155 
| Copy update example |
|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/3d1a503b-a0ac-4c8d-b4bb-7b42cdb36cfa" width="320px">|
=> fix: ios: #2155: Fix issues on Sign Specs / Metadata screen

android/src/main/java/io/parity/signer/components/networkicon/IdentIconImage.kt, android/src/main/java/io/parity/signer/components/networkicon/IdentIconWithNetwork.kt, android/src/main/java/io/parity/signer/components/sharedcomponents/KeyCard.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsScreenSubgraph.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/export/KeySetDetailsExportResultBottomSheet.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/export/KeySetDetailsMultiselectBottomSheet.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/exportroot/KeySetRootExportBottomSheet.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/items/SeedKeyDetails.kt, android/src/main/java/io/parity/signer/screens/keysetdetails/seedselectmenu/KeySetItem.kt, android/src/main/java/io/parity/signer/screens/scan/transaction/transactionElements/TCAuthorPublicKey.kt, android/src/main/java/io/parity/signer/screens/scan/transaction/transactionElements/TCTypesInfo.kt, android/src/main/java/io/parity/signer/screens/settings/logs/logdetails/HistoryCardExtended.kt, android/src/main/java/io/parity/signer/screens/settings/networks/details/NetworkDetailsScreen.kt, android/src/main/java/io/parity/signer/screens/settings/networks/signspecs/view/SignSpecsResultBottomSheet.kt
updated export screen into new design
|-|-|
| ![image](https://github.com/paritytech/parity-signer/assets/11879032/a3419146-1067-4138-ab31-40c96cc67a80) | ![image](https://github.com/paritytech/parity-signer/assets/11879032/b9ee7a02-542a-42ea-99f1-fb44b01e3044) |
=> feat: android update export keys design

ios/PolkadotVault/Components/Buttons/QRCodeButton.swift
Fixes invalid layout for qr code icon
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/370cd3c9-2dba-4bde-99ff-96bd4976c6e1" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/42cfeeee-304a-4b56-b963-b105f2500fdc" width="320px">|
=> feat: ios: update design for qr code button

ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift
Fix issue with deletion of key set after recent view model refactor and technical improvements
| Fix |
|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/a21ea2f3-8193-4bde-b5ad-5924366355cb" width="320px">|
=> feat: ios: fix issue with delete key set

android/src/main/java/io/parity/signer/screens/settings/logs/LogsSubgraph.kt, android/src/main/java/io/parity/signer/screens/settings/logs/logdetails/LogDetails.kt
fix #2160
fixed animations for settings screen - side to side
=> fix: android transaction animations for log statements

android/src/main/java/io/parity/signer/domain/storage/SeedRepository.kt, android/src/main/java/io/parity/signer/domain/storage/SeedStorage.kt, ios/PolkadotVault/Core/Keychain/SeedsMediator.swift
Removing tell rust seed names as we don't use rust state machine and they don't need to know seed names anymore
=> feat: removing tell rust seed names from mobile clients

android/src/main/res/values/strings.xml, build.gradle
update gradle plugin and update wording in dynamic derivations screen
=> feat: Android upd agp and copy

ios/PolkadotVault/Modals/Alerts/HorizontalActionsBottomModal.swift, ios/PolkadotVault/Modals/Alerts/VerticalActionsBottomModal.swift, ios/PolkadotVault/Modals/Errors/ErrorBottomModal.swift, ios/PolkadotVault/Resources/en.lproj/Localizable.strings, ios/PolkadotVault/Screens/Scan/DynamicDerivations/AddDerivedKeysView.swift
Updated design and logic for Add Derived Keys flow
https://github.com/paritytech/parity-signer/assets/1955364/a9c84fd9-48f5-4940-9f93-97e117419a84
=> feat: ios: update design and flow for derived keys

ios/PolkadotVault/Screens/Scan/DynamicDerivations/AddDerivedKeysView.swift, ios/PolkadotVaultTests/Core/PasswordProtectionStatePublisherTests.swift
Improvements for empty key set case for add derived keys flow
https://github.com/paritytech/parity-signer/assets/1955364/714c7bda-7526-4e45-bd60-dcaae71ee493
=> fix: ios: Fix and improve Add Derived Keys screen interactions

README.md, ios/PolkadotVault.xcodeproj/project.pbxproj
Update SwiftFormat and SwiftGen tooling to automatically install and upgrade via homebrew
=> chore: ios: update SwiftFormat and SwiftGen tooling

docs/src/tutorials/Start.md
with release link and no need to use dark scheme - list supported as well
=> docs: updated documentation

android/src/main/java/io/parity/signer/screens/createderivation/derivationsubscreens/DeriveKeyNetworkSelectScreen.kt
Update new derivation added preview for disabled state
consider update primaby button disabled stated (globally?), old version looks like
|-|-|
| ![image](https://github.com/paritytech/parity-signer/assets/11879032/82b00740-9469-4f2b-bc55-b3fb5cbb2086) | ![image](https://github.com/paritytech/parity-signer/assets/11879032/281181dc-56aa-4dbf-ade8-786b394a9e4b) |
Waiting for colors clarification.
=> feat: android uddate new derivation. 

rust/Cargo.lock, rust/navigator/Cargo.toml, rust/navigator/src/error.rs, rust/navigator/src/lib.rs, rust/signer/src/lib.rs, rust/signer/src/signer.udl
Add endpoints to create BananaSplit shares and generate passphrases
- add `bs_encrypt`
- add `bs_generate_passphrase`
=> feat: BananaSplit encrypt

android/src/main/java/io/parity/signer/screens/scan/camera/CameraViewModel.kt
see scanning in system tracing android.
=> feat: android adding scan tracing

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Core/AppDelegate.swift, ios/PolkadotVault/PolkadotVaultApp.swift
Disable ability to use custom keyboard globally in the app
=> feat: disable custom keyboard globally

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Core/Authentication/DevicePasscodeAuthenticator.swift, ios/PolkadotVault/Core/ServiceLocator.swift, ios/PolkadotVault/Screens/Logs/Views/LogNoteModal.swift, ios/PolkadotVault/Screens/Logs/Views/LogsListView.swift
This adds authentication with passcode before user clears logs, as it was raised as security concern
=> feat: ios: authenticate user before clearing logs

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ios/PolkadotVault/Core/AppDelegate.swift, ios/PolkadotVault/Core/Runtime/RuntimePropertiesProvider.swift, ios/PolkadotVault/Screens/DerivedKey/CreateKeyNetworkSelectionView.swift, ios/PolkadotVault/Screens/Scan/Services/CameraService.swift, ios/fastlane/lanes/lane_build.rb, ios/fastlane/lanes/lane_tests.rb
Update for:
- SPM dependencies
- SwiftLint version and plugin integration
- related updates
- removing unnecessary `print` as was flagged by MobSF
=> chore: ios: dependencies update and cleanup

ios/PolkadotVault/Core/Keychain/SeedsMediator.swift, ios/PolkadotVault/Screens/Containers/AuthenticatedScreenContainer.swift, ios/PolkadotVaultTests/Core/Keychain/SeedsMediatorTests.swift
Fixing UI refresh issue that surfaced when moving Settings to different navigation stack.
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/4366ce60-8d03-4aca-927b-266dadba8dd7" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/be49b95d-866b-4df6-bc5d-5c3e2f3cc9c9" width="320px">|
=> fix: ios: Wipe All does not update main view

ios/PolkadotVault/Core/JailbreakDetectionPublisher.swift
Updating list of jailbreak detection paths to newest one I could find
=> chore: ios: update jailbreak detection paths

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Backend/Services/BananaSplitService.swift
iOS wrapper for banana split functions, to be used in new functionality
=> feat: ios: bs service

.github/workflows/android-app.yml, .github/workflows/android-release.yml
Fix android build
- change `sdkmanager` path
=> fix: android build

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecsListView.swift, ios/PolkadotVault/Screens/Settings/Subviews/VerifierCertificate/VerifierCertificateView.swift, ios/PolkadotVaultTests/Models+Generate/MKeyDetails+Generate.swift, ios/PolkadotVaultTests/Screens/Settings/Subview/NetworkSelectionSettings/NetworkSettingDetailsViewModelTests.swift, ios/PolkadotVaultTests/Screens/Settings/Subview/SignSpecs/SignSpecsListViewModelTests.swift, ios/PolkadotVaultTests/Screens/Settings/Subview/VerifierCertificate/VerifierCertificateViewModelTests.swift
Increasing unit test coverage by new tests for view models
=> chore: ios: Add unit tests for network setting details, verifier certificate, sign specs list

rust/Cargo.lock
=> fix: cargo deny

ios/.swiftformat, ios/Packages/Blockies/Sources/Blockies/BlockiesImageRenderer.swift, ios/Packages/Blockies/Sources/Blockies/Helpers/PlatformColor.swift, ios/Packages/Jdenticon/Sources/Jdenticon/Drawing/Graphics.swift, ios/Packages/Jdenticon/Sources/Jdenticon/Drawing/IconGenerator.swift, ios/Packages/Jdenticon/Sources/Jdenticon/Drawing/Shapes.swift, ios/Packages/PolkadotIdenticon/Sources/PolkadotIdenticon/Helpers/IdenticonColorsGenerator.swift, ios/Packages/PolkadotIdenticon/Sources/PolkadotIdenticon/Models/Color.swift, ios/Packages/PolkadotIdenticon/Sources/PolkadotIdenticon/Public/PolkadotIdenticonView.swift, ios/PolkadotVault/Backend/Services/CreateDerivedKeyService.swift, ios/PolkadotVault/Core/ServiceLocator.swift, ios/PolkadotVault/RustDataExtensions/Verifier+Show.swift, ios/PolkadotVault/Screens/Containers/AuthenticatedScreenContainer.swift, ios/PolkadotVault/Screens/KeyDetails/ExportKeys/ExportKeysSelectionModal.swift, ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift, ios/PolkadotVault/Screens/Logs/Models/LogEntryRenderable.swift, ios/PolkadotVault/Screens/Scan/CameraView.swift, ios/PolkadotVault/Screens/Scan/Models/TransactionSummaryModels.swift
Update configuration file and codebase to SwiftFormat 0.53.0
=> chore: ios: update to SwiftFormat 0.53.0

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Core/Authentication/DevicePasscodeAuthenticator.swift, ios/PolkadotVault/Screens/Logs/Models/LogEntryRenderable.swift, ios/PolkadotVault/Screens/Logs/Views/LogNoteModal.swift, ios/PolkadotVault/Screens/Logs/Views/LogsListView.swift, ios/PolkadotVaultTests/Models+Generate/MLog+Generate.swift, ios/PolkadotVaultTests/Models+Generate/MTransactionCardSet+Generate.swift, ios/PolkadotVaultTests/Screens/Logs/LogNoteModalViewModelTests.swift, ios/PolkadotVaultTests/Screens/Logs/LogsListViewModelTests.swift
Test coverage for Logs related screens
=> chore: ios: test coverage for log list / details view models

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetSeedPhraseView.swift, ios/PolkadotVaultTests/Screens/CreateKey/RecoverKeySet/RecoverKeySetNameViewModelTests.swift, ios/PolkadotVaultTests/Screens/CreateKey/RecoverKeySet/RecoverKeySetSeedPhraseViewModelTests.swift, ios/PolkadotVaultTests/Screens/NoKeySets/NoKeySetsViewModelTests.swift
Unit test coverage for Recover Key Set flow and No Key Sets screen
=> chore: ios: Unit tests for recover key set and no key sets

android/build.gradle
releasing new version android 6.3.1 with security and performance fixes
=> feat: releasing android 6.3.1

ios/PolkadotVault.xcodeproj/project.pbxproj, ios/PolkadotVault/Backend/Services/CreateDerivedKeyService.swift, ios/PolkadotVault/Modals/Alerts/HorizontalActionsBottomModal.swift, ios/PolkadotVault/Modals/Errors/ErrorBottomModalViewModel.swift, ios/PolkadotVault/Resources/en.lproj/Localizable.strings, ios/PolkadotVault/Screens/Scan/DynamicDerivations/AddDerivedKeysView.swift, ios/PolkadotVaultTests/Screens/CreateKey/RecoverKeySet/RecoverKeySetNameViewModelTests.swift
Do not safe dynamic derived keys after dismissing "Add Derived Keys" screen
- remove save functionality
- bump version to 6.3.2 so we can release TF build
=> feat: disable dd keys saving and bump to 6.3.2

ios/PolkadotVault/Resources/en.lproj/Localizable.strings, ios/PolkadotVault/Screens/Scan/DynamicDerivations/AddDerivedKeysView.swift
| Example | |
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/6a5a31ce-b7f7-4070-ad98-3d92a82f05ee" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/4ea15ead-3764-41e3-b386-6a01d6bbb55a" width="320px">|
=> feat: ios: update dd add keys ui

rust/parser/src/decoding_older.rs
=> fix: clippy rust 1.76

android/build.gradle
=> feat: android compose update dependencies

rust/Cargo.lock, rust/qr_reader_phone/Cargo.toml, rust/qr_reader_phone/src/error.rs, rust/qr_reader_phone/src/process_payload.rs
=> feat: validate seed on BS recovery

ios/PolkadotVault.xcodeproj/project.pbxproj
Updating minimum required version to highest patch version supported by iPod Touch
=> feat: ios: Update minimum target for iOS 15 devices to exact patch version

docs/src/about/Changelog.md, rust/definitions/src/metadata.rs, rust/generate_message/src/lib.rs
=> chore: fix some comments

rust/db_handling/src/interface_signer.rs, rust/generate_message/src/helpers.rs, rust/transaction_signing/src/sign_transaction.rs
=> fix: fixed clippy style issues

.github/actions/install-android-dep/action.yaml, .github/workflows/android-app.yml, .github/workflows/android-release.yml, .github/workflows/docs.yml, .github/workflows/opencv-docker.yml, .github/workflows/rust-clippy.yml, .github/workflows/rust-test-android.yml, docker/opencv.Dockerfile, rust/Cargo.lock, rust/qr_reader_pc/Cargo.toml, rust/qr_reader_pc/src/lib.rs
=> fix: use latest opencv on ubuntu

android/src/main/java/io/parity/signer/domain/storage/SeedStorage.kt
Previosuly banana split passwords were written to the same encrypted preferences file as seeds themselves. Which resulted in  `getSeedNames` returning bs password entries as seed names with a possibility to select them. More confusingly, the selected keyset details screen still shows previous keyset in such an attempt to select bs password as selected keyset. Also this causes https://github.com/novasamatech/parity-signer/issues/2472 when attempting to create a bs backup in such cases
Store bs password in the completely separate encrypted preferences file, that is constructed based on the same master key
This way, seeds and their associated values are completely separated from each other
=> fix: banana split passwords appear as keysets

ios/PolkadotVault.xcodeproj/project.pbxproj
PR updates iOS app version to 7.0.0
=> chore: update iOS app version to 7.0.0

rust/Cargo.lock, rust/db_handling/src/db_transactions.rs, rust/transaction_parsing/Cargo.toml, rust/transaction_parsing/src/error.rs, rust/transaction_parsing/src/message.rs, rust/transaction_parsing/src/tests.rs, rust/transaction_signing/src/sign_transaction.rs, rust/transaction_signing/src/tests.rs
The PR enables the signing of the non utf8 messages ensuring that the payload is wrapped into `<Bytes>...</Bytes>` tag
Closes #2431
=> feat: signing of non-utf8 messages

.github/workflows/android-manual-gplay.yml, android/build.gradle
These changes allow to create GitHub release with apk files after Google play deploying.
=> feat: add GitHub releases to CI
