novasamatech/parity-signer

.travis.yml
src/components/AccountDetails.js
src/components/AccountPin.js
src/components/AccountSeed.js
src/components/App.js
src/containers/AccountNew.js
src/containers/AccountPin.js
src/styles/index.js

- Input for brain wallet is auto-adjustable
- Selectable values on Acount Details
- PINs are now masked and numeric (Closes #15 and closes #13 )
- Buttons on PIN screens (Closes #5) although I think it would be better to put in in the topbar, but it's a bit more complicated.

Fixing PIN screens

---

rust/signer/Cargo.lock
rust/signer/Cargo.toml
setup_linux.sh

@debris 
Could you check whether this broke something, because I had to push it with ```--no-verify``` but I think it is due to Linux and not being able to run iOS and watchman without problems.

Update to rustup and update ethkey and rlp dependency

---

.gitlab-ci.yml
gen_key.sh

Add example gitlab-ci and script to generate test key for apk signing.
@fckt this is what we were using in the gitlab tests. Not sure if you want to tighten up the key generation or add any other stages to the .gitlab-ci.yml ... 
Let me know.

Gitlab CI for parity-signer

---

create-ndk-standalone.sh

Note that `brew install android-ndk` returns `Error: No available formula with the name "android-ndk" ... It was migrated from homebrew/core to homebrew/cask.`

fix: Update script instructions command to install NDK

---

README.md
android/app/src/main/java/io/parity/signer/EthkeyBridge.java
ios/EthkeyBridge.1.swift
ios/NativeSigner/EthkeyBridge.swift
rust/signer/Cargo.lock
rust/signer/Cargo.toml
rust/signer/Makefile
rust/signer/signer.h
rust/signer/src/eth.rs
rust/signer/src/lib.rs
rust/signer/src/util.rs
src/components/AccountSeed.js
src/constants.js
src/screens/AccountBackup.js
src/util/account.js
src/util/native.js
yarn.lock

This is squashed #223 to date with fixed Rust dependencies that should hopefully forever solve all of our build issues (no linked C code).
It includes the BIP39 for Ethereum (new phrases are BIP39, recovery attempts BIP39 recovery and falls back to Parity phrases) along with minor UI changes (phrase validation and making the boxes bigger as 24 word BIP39 phrases are just longer).
#223 will be rebased after this is merged.

Fixed Rust dependencies + BIP39 support

---

README.md

There was a typo, fixed from Andrid to Android

Updating typo in README

---

src/components/AccountCard.js
src/screens/AccountNew.js
src/screens/AccountRecover.js
src/stores/AccountsStore.js
src/util/account.js

- add validBip39Seed to new account's state in `AccountStore`
- only mark the recovery field as valid if the bip39 checksum passes
- show in the account card the seed type
- warn users if they recover a brain wallet (e.g no bip39 type)
Here is how it looks: (valid bip39, invalid bip39, warning)

Show seed type and green field if valid bip39

---

src/screens/AccountBackup.js

- Tested on Android for both account creation and "view backup phrase" scenario.
- first scenario tested by hardcoding an incredibly long phrase as the seed of any new account. It get showed entirely and the screen is scrollable
- second simply by recovering an extremely long phrase and then going to account>show recover phrase
- addresses https://github.com/paritytech/parity-signer/issues/248 but possibly not entirely as only one character is truncated..
- note that I didn't touch the recovery phrase input field as this one is scrollable.

Flexible text box for recovery phrase

---

src/screens/AccountRecover.js
src/stores/AccountsStore.js

- closes https://github.com/paritytech/parity-signer/issues/261(the second bug mentioned)
Users could set a seed for the `new` account in `AccountRecover`. This seed remained in the `AccountStore` state upon unmount. It needed to be manually removed in case a user doesn't finish the process.

Make sure the recovery phrase is emptied upon process abortion

---

android/app/src/main/AndroidManifest.xml

- closes https://github.com/paritytech/parity-signer/issues/169
- closes https://github.com/paritytech/parity-signer/issues/122
I just followed https://facebook.github.io/react-native/versions the `SYSTEM_ALERT_WINDOW` is now automatically removed as of RN 0.60

Fix unneeded permissions

---

src/screens/AccountRecover.js
src/stores/AccountsStore.js
src/util/account.js

- closes https://github.com/paritytech/parity-signer/issues/203
- alphabetical order cleanup
An empty account never got persisted in storage (since https://github.com/paritytech/parity-signer/pull/235/files) however it was still added to the `AccountStore` state and ended up being listed on the account overview. This doesn't happen anymore.
We now also don't allow users to recover an account with an empty seed.

Don't allow empty seed phrase recovery

---

package.json
src/screens/AccountNew.js
src/screens/AccountRecover.js
src/stores/AccountsStore.js
src/util/debounce.js
yarn.lock

- debounce is now debouncing.
- icon selection isn't lagging anymore.
- removed a direct dependency to `debounce`
What it effectively solves:
On account recovery, debounce is working, the device used to calculate the address at every key stroke. Now it's effectively debouncing (after/before):
On new account, the icon selection doesn't re-render.
I do exactly the same in each example, I click on new account and click on the 4 first icons **consecutively**. You can see the selection is jumping. (before/after)

Refactor updateNewAccount

---

android/app/src/main/AndroidManifest.xml
src/components/AccountSeed.js
src/components/KeyboardScrollView.js
src/screens/AccountNew.js
src/screens/AccountRecover.js

fix #278 
* 96c3539: fix double tap problem on Android and half covered text input on iOS related to
#268
* 10e97b4: every click on seed input field will trigger scroll 
* 0d29f30: align seed input to top on android, so iOS and Android are same now
* b40b6da: prettier the code and remove useless import
Screenshots here (too big cannot upload on Github):  
https://drive.google.com/file/d/1g-o_XmShquI9U52agOQUl4VBX9jBujOE/view

Fix keyboard aware scroll view related problem

---

android/app/build.gradle
android/app/src/main/java/io/parity/signer/MainActivity.java

close #230 
Self explained.
Use negative value `!BuildConfig.DEBUG` for comparison since it has only been tested on `DEBUG` mode now.

fix: enable screenshot in dev mode

---

src/components/AccountSeed.js

closes #269 
Currently autoComplete function in Android does not work as expected, it is a known issue of [React Native](https://github.com/facebook/react-native/pull/25549), we need bump React Native when the fix is included into new React Native release.

fix: disable auto complete when user input recovery phrase

---

package.json

self explanatory. I keep doing `yarn start` because it's a standard.. and end up with an ios error..

Yarn start for react-native start preventing out of memory

---

package.json
yarn.lock

- closes: https://github.com/paritytech/parity-signer/issues/299 after https://github.com/paritytech/react-native-secure-storage/pull/8
tested successfully on android

Pull react-native-secure-storage from Parity repo

---

android/app/src/main/java/io/parity/signer/EthkeyBridge.java
ios/NativeSigner/EthkeyBridge.swift

`keccak` and `blake2s` should `reject` when fed ill-formatted data.

fix: Error handling for hash functions

---

src/components/QrView.js
src/util/account.js

My bad, I've messed that up in the account management PR.
The accountId used to have `0x`, like [here](https://github.com/paritytech/parity-signer/blob/eb55ff68bb1dddc861c72205de72168502f5edc6/src/util/account.js#L11) and also specified in the [ERC](https://github.com/ethereum/EIPs/issues/67).
Right now this prevents MyCrypto from actually reading the account.

Ethereum accountId should have a 0x

---

src/screens/QrScanner.js
src/stores/ScannerStore.js
src/util/decoders.js

fix #247 
mainly 3 fixes:
a15259d: fix a scanning user UX issue, after unavailable QR code, only trigger the scan when the user clicks the button.
b5e239f: add address detected warning.
eaf9f52: remove an unhandled promise rejection warning, code should return when error detected.

QR Code Scanner Fixes

---

src/stores/AccountsStore.js
src/util/account.js

close #323 .
No archived account anymore, delete the account when user press the button.

fix: delete account

---

android/app/build.gradle

closes : https://github.com/paritytech/parity-signer/issues/350
tested:
- build an apk and add to the google playstore console --> accepted (unlike before).
- install with `yarn start` and `yarn android` --> can do screenshots.
- install release apk --> can't do screenshots.

Make release flag implicit

---

src/stores/ScannerStore.js
src/util/decoders.js

fixes #348
This will match the account prefix based on the payload genesis hash.
In case user is signing a message or a hash, and the address provided couldn't be found in store, it'll do one more pass with the dev chain prefix encoding to search.

onScan find Address in Store with Appropriate Prefix

---

src/screens/AccountList.js
src/screens/AccountNetworkChooser.js
src/screens/SignedTx.js
src/screens/TxDetails.js
src/stores/ScannerStore.js

The property protocol is linked to a network, it should not be linked to an account directly (an account has a network key, which gives us the protocol).
- needed for https://github.com/paritytech/parity-signer/pull/352 so that I don't have to create a protocol property for new accounts.
Tested on Android for Eth and Polka Dev account

chore: Refactor protocol

---

.editorconfig

As we are using "tabs" instead of "spaces" on Javascript file, Github show the indentation of tab always as 4 spaces, it will make confusion when we check the diff on Github, especially for #337.

chore: show tab correctly

---

src/stores/ScannerStore.js
src/util/array.js
src/util/decoders.js

As #337 includes so many file changes.
Here I cherrypicked some errors catched by ESLint, which could be merged earlier to prevent any bugs on V3.
1. The undefined value should be changed:
`parseData` -> `parsedData`
`rawAfterFrames` -> `uosAfterFrames`
2. One redundant line `result.push(lword);` should be deleted

fix: some code fix catched by eslint

---

src/screens/AccountBackup.js

closes #363 
- allow seed phrase copy only for dev environment
- show the "copy these words" at any time, not only at account creation.
edit: tested by building an apk, nothing happen on press as expected.

fix: only allow copying seed phrase in dev environment

---

src/screens/AccountBackup.js
src/screens/AccountNetworkChooser.js

close #363 .
1. Clear the state when choosing the new network. (Which may cause more bugs if user switch network between Substrate and Ethereum).
2. Copy the seed when creating an Ethereum account in DEV mode. 
Fixed behaviour here:

fix: clear account state when changing network

---

src/constants.js

- uses the Kusama cc2 genesis hash (using polkascan or apps -> tools -> chain.getBlockHash(0))
"0xe3777fa922cafbff200cadeaea1a76bd7898ad5b89f7848999058b50e715f636"
Tested with apps, could sign the tx, got "error 1010", as expected since transfer aren't enabled.

chore: Use Kusama cc2 genesis hash

---

.github/semantic.yml
package.json
yarn.lock

1. remove any restrictions on commit
2. add semantic validator to add the following [types](https://github.com/paritytech/parity-signer/compare/hanwen-git-hook?expand=1#diff-ad4346b0676b8cc8daabacb6e255e307R4-R15) in front of the PR as what we do before with commit.  @goldsteinsveta
Since I can not change the settings of the repo, to use it we still need to do followings administration with this repo:
Install Semantic Pull Request on Github, start [here](https://github.com/apps/semantic-pull-requests/installations/new/permissions?target_id=6014309).
Another thing is that I suggest we only allow [Squash Merging](https://help.github.com/en/articles/configuring-commit-squashing-for-pull-requests) under merge button.
If after this PR you still met the restrictions with commit, please delete …

chore: remove git restrictions with pre-git and add semantic validator for pr

---

src/components/AccountCard.js
src/components/AccountIcon.js
src/components/AccountSeed.js
src/constants.js
src/screens/AccountBackup.js
src/screens/AccountDetails.js
src/screens/AccountEdit.js
src/screens/AccountList.js
src/screens/AccountNetworkChooser.js
src/screens/AccountPin.js
src/screens/AccountUnlock.js
src/screens/Loading.js
src/screens/MessageDetails.js
src/stores/AccountsStore.js
src/stores/ScannerStore.js
src/util/account.js
src/util/db.js

closes #389 
How to test:
- create a Kusama account (1)
- modify the genesisHash aka `networkKey` of Kusama in `src/constants.js`
- reload the App
Because the  genesisHash used to create (1) isn't known any more, we can't match the Kusama Network. Still this account can be seen, its backup retrieved with the pin and deleted.
edit:
This was quite a painful PR, trying to remove many weird things that were done. Now we use the same [key, value] mapping in the accountStore and in the db. This allows to show accounts which we have no corresponding `NetworkKey`. It also helps to seemlessly save or delete accounts (even if the network is not known) because the db and the store have the same keys.
This PR introduces the notion of `selectedKey` that corresponds to a `selectedAccount` (more broadly …

feat: Show accounts with unknown network

---

src/screens/AccountPin.js

fix #403  
screenshot on iPhone SE @laboon
Also click on the blank place will hide the keyboard.

fix: use keyboard scroll view for pin input screen

---

package.json
yarn.lock

ESLint does not works as expected, this fix the `no-unused-var` error in "for.. in" of Javascript, and revert previous workaround.
Eslint evaluate `no-unused-var` for the keys in "for.. in" loop with eslint-babel: 10.0.1, which discussed [here](https://github.com/eslint/eslint/issues/12117).
So we have changed the dependency version, but this is still used in @react-native-community/eslint-config, and @react-native-community/eslint-config is rarely updated.
Though I have changed the code in `yarn.lock`, but every time we add new dependencies, remove dependencies, the lock file will be rewrite. It will further cause the original issue, it is just not the correct way to lock dependency's version.
So the correct way to do that is with yarn's …

chore: lock the version of eslint-babel

---

rust/signer/Cargo.lock
rust/signer/Cargo.toml
rust/signer/src/lib.rs

Most notably: `ethsign` with patched `libsecp256k1`
CC @s3krit

chore: Bump dependencies

---

.travis.yml
README.md
android/app/build.gradle
android/app/src/androidTest/java/io/parity/signer/DetoxTest.java
android/build.gradle
e2e/config.json
e2e/firstTest.spec.js
e2e/init.js
e2e/testIDs.js
package.json
scripts/fix-rn-camera-path.sh
src/components/Button.js
src/screens/AccountList.js
src/screens/TermsAndConditions.js
yarn.lock

This is the configuration part of #326 which enable us to run CI locally.
For test it locally you need install `detox-cli` as global npm dependency. it has conflict with local `detox` dependency so that we could not add it locally and start with `npx`
```
npm install -g detox-cli
```
After testing with Cavy and Detox, I find Detox is a better choice for us, since we want to develop the test and the origin code base at the same time. And the only complex part of Detox is the configuration part, to use it we do not to use High Order Component, but just with an `testID` on the component. It is more powerful and It is in active development by Wix team.
There are some comparison articles like [Detox vs Appium](https://medium.com/reactive-hub/detox-vs-appium-ui-tests-in-react-native-2d07bf1e244f …

test: Add integration(e2e) test

---

android/build.gradle
src/App.js

- closes #447 
- update gradle to 3.5.1 (Android Studio kept asking me to)
The header brings back the usual behavior on Android of not having any header title. Please make sure that it looks ok on iphone (the home as well as the other screens).

fix: Header and upgrade gradle

---

android/app/src/main/java/io/parity/signer/MainActivity.java
ios/NativeSigner/AppDelegate.m
src/App.js

Create the bindings for launchArgs, which could be useful now to detect the detox e2e environment and set mock methods.
The launchArgs in ios would be an array with following strings ( It wouldn't be empty, at least contain the path): 
The launchArgs in Android is an object, return null if there is no args:
We could cal `global.inTest` to check if it is a test runtime.

test: add test arguments for e2e test

---

src/screens/About.js
src/screens/AccountBackup.js

This code was just tiny little "nice to have" but it's responsible for one of the error that `./android/gradlew assembleRelease` throws when building an unsigned apk: 
> Error: package is not a valid resource name (reserved Java keyword)
This is solved by react-native `0.61` but for now I just want to see what the CI bumps into next.

fix: remove version in "About" to fix CI

---

.gitignore
specs/util/identitiesUtils.spec.js
src/screens/AccountNetworkChooser.js
src/screens/IdentityBackup.js
src/screens/IdentityManagement.js
src/screens/MessageDetails.js
src/screens/PathDerivation.js
src/screens/PathDetails.js
src/screens/TxDetails.js
src/stores/AccountsStore.js
src/stores/ScannerStore.js
src/stores/types.js
src/util/identitiesUtils.js
src/util/navigationHelpers.js

Naming is the most difficult problem.
Renaming `seed` to `seedPhrase` if phrase is used.
In schema we use `encryptedSeed` since password will also used to secure that in the future version.

chore: renaming to seedPhrase when phrase is used

---

src/stores/ScannerStore.js

closes #496 .
It is not a problem with "this is sparta" account, it is a problem if recipent is not a recognized account in Ethereum.
Create any ethereum account, scan any transaction QR with an unrecognized destination address, error happens.
The bug affect so widely and is so obvious, I am feeling guilty for creating it, we will need to release a fix version soon.

fix: error with new recipient account

---

package.json
specs/util/decoders.spec.js
specs/util/units.spec.js
src/components/PayloadDetailsCard.js
yarn.lock

The `Decorated` class I imported from `@polkadot/metadata`, is actually for completely offline uage. (Or rather enables it). It is not actually metadata, it is a decorated version that wraps metadata. So it actually has a metadata getter as well.
It would be simple to just use `Metadata` from `@polkadot/types` instead, which also removes the additional dependecy of `@polkadot/metadata`
It mainly affect the decoding process, how to test:
1. run `yarn test`, all tests in `decoder.spec.js` should passed.
2. It should be possible to sign any extrinsics on CC3.

fix: use Metadata properly, not with the wrapped Metadata

---

.eslintrc.js
package.json
src/App.js
src/screens/SignedMessage.js
src/screens/SignedTx.js
src/util/native.js
yarn.lock

The useful eslint plugin helps find import errors.
It found duplicated import, unused export in our code base, and legacy react native import syntax.

test: add eslint-plugin-import validation

---

src/components/AccountSeed.js
src/components/ButtonNewDerivation.js
src/screens/IdentityNew.js
src/screens/IdentityPin.js
src/screens/PathDerivation.js

closes #485 
Imporve text input on Identity New, Identity Pin and Path Derivation screen.
* remove autofocus for Identity New and Path Derivation screen.
* remove suggestions when creating path  and when recovering identity
* adjust extra height for keyboard scroll view which enble showing confirm button on small screen devices. (Basically, for every KeyboardScrollView, the `extraHeight` need to be specified to enble scroll up the screen for focused text input)
|Android|Ios|
|---|---|
|![out](https://user-images.githubusercontent.com/6014309/71217740-0a973100-22bf-11ea-9f98-6380c542bef9.gif)|![out_ios](https://user-images.githubusercontent.com/6014309/71217743-0ec34e80-22bf-11ea-95fb-0ead0cb378c9.gif)
On a small screen device, try the text input in the following screens
* recover identity …

fix: extra height, focus, suggestions in text input

---

src/screens/PathDerivation.js

closes #507 .
It works as same as expected behaviour in the issue description.

fix: custom path derivation with known network

---

docs/privacy-policy.md.js
docs/terms-and-conditions.md.js
src/components/ScreenHeading.js
src/screens/Security.js

closes #509 
Following is the current screenshots with this PR, 
The problem for second-lever nested item is related to [react-native-markdown-renderer](https://github.com/mientjan/react-native-markdown-renderer). 
I did not fix the problem with the library but extract them from the list to solve most of the problem.
|Disordered text | format been cleared| all top-lever list number is 1|
|---|---|---|
|<img width="367" alt="Screen Shot 2019-12-28 at 14 12 07" src="https://user-images.githubusercontent.com/6014309/71544230-bb1aca00-297c-11ea-8eca-2c990cbec695.png">|<img width="363" alt="Screen Shot 2019-12-28 at 14 11 47" src="https://user-images.githubusercontent.com/6014309/71544236-ca9a1300-297c-11ea-9364-47260a1e6212.png">|<img width="363" alt="Screen Shot 2019-12-28 at 14 11 28" …

fix: UI problem on v4.0.5

---

src/components/CustomScrollView.js
src/screens/About.js
src/screens/PrivacyPolicy.js
src/screens/TermsAndConditions.js

closes #375 
[indicatorstyle](https://facebook.github.io/react-native/docs/scrollview#indicatorstyle) prop for setting the color of scroll bar is only available on ios. So I create a custom scroll bar wrapper for that. To prevent to be an overkill, I use the simplist implementation, I think it is enough for a scroll bar.
Screenshots on ios and android, also tested in terms and condition view with agree button.

fix: add custom scroll view with custom scroll bar

---

src/screens/PathDetails.js

After delete all the paths in one of the Substrate network, it will still navigate back to the path list of this network. It would be better to navigate back to the network chooser screen.
|Before Fix| After Fix|
|---|---|
|![beforeDelete](https://user-images.githubusercontent.com/6014309/71717177-7a590000-2e17-11ea-867e-37a1f76e7e76.gif)|![afterDelete](https://user-images.githubusercontent.com/6014309/71717085-30701a00-2e17-11ea-8ca1-2e6ed87ee65c.gif)|

chore: fix navigation after path deletion

---

android/app/src/main/java/io/parity/signer/EthkeyBridge.java
ios/NativeSigner/EthkeyBridge.m
ios/NativeSigner/EthkeyBridge.swift
rust/signer/signer.h
rust/signer/src/lib.rs
src/components/Button.js
src/screens/IdentityBackup.js
src/util/native.js

closes #405 
Behavior on iOS and Android as following:
@goldsteinsveta  do you have any suggestions about the two new buttons?

feat: add support for 12 mnemonic option

---

e2e/e2eUtils.js
e2e/identityManipulation.spec.js
src/screens/IdentityNew.js
src/screens/IdentityPin.js
src/screens/PathDerivation.js

closes #518 , #519
4a30916 : is for #518, now the text is changed, and all the text in `IdentityNew` is ordered into a object/map called `t`.
The other three commits are for #519 , the main fix is in dc8d65e , which add `onSubmitEditing` for TextInput Component. Other two commits is mainly for e2e tests.
The unfunctioned button is not only in Android but also in iOS, now I have address all the return button in both platforms:
1. in path derivation process, path input and account name input.
2. in pin unlock screen, pin input
3. in pin creation screen, pin input
4. in path recovery screen, seed input
for above 1 and 2, try create any path from a Kusama network:
for above 3 and 4, try recovery an identity with any seed:
|android|ios|
|---|---| …

fix: pin input text and return button

---

specs/util/identitiesUtils.spec.js
src/screens/AccountDetails.js
src/screens/AccountNetworkChooser.js
src/screens/PathDerivation.js
src/screens/PathDetails.js
src/screens/PathManagement.js
src/screens/PathsList.js
src/util/alertUtils.js

A small feature which ease the path creation process.
How to test:
Select Kusama network -> select any path -> tap top right menu button -> tap "Derive Account" button -> path derivation card should be a pre-filled path, and path creation should be correct.
At the same time, other path derivation should keep the same as before, which is:
1. network path derivation: Network selection screen tap "Kusama" -> tap "Create New Derivation" button -> behavior same as before
2. custom path derivation: Network selection screen tap "Add Network Account" -> Scroll to bottom and choose "Create Custom Path" -> behavior same as before

feat: enable path derivation from existed path card

---

specs/util/identitiesUtils.spec.js
src/screens/PathsList.js
src/util/identitiesUtils.js
src/util/regex.js

close #522 
The bug is caused by the incorrect sorting function in `identitiesUtils.js`
Fix the bug and refactor the test suit in `identitiesUtils.spec.js`, which make it easy to add more cases.
Also now the unknown paths will be grouped by the first catch group of path.
In the following example  `/soft/path`, `/soft/222`, `/soft/333` will be grouped together under `/soft`
Signing tested successfully on iOS.

fix: display soft derivation custom path

---

src/components/AccountSeed.js
src/screens/IdentityNew.js
src/util/account.js

close #529 .
Now after tapping the suggestion text, the trailing space will be automatically added.
And for a 24 words recovery phrase, it will not add the whitespace to the end.
But for a 12, 15, 18, or 21 words (They should all be possible to be recovered), the trailing whitespace is still added, but after tapping the "Recover Identity" button and input PIN, it will automatically be trimmed.
Test cases:
1. tapping any suggestion word, a whitespace should follow.
2. move the cursor to middle, and add another suggestion word, no extra trailing whitespace in the end should be added.
3. After input bip39 mnemonic phrase, the box border should not be red though there is a trailing whitespace.
4. after  input bip39 mnemonic phrase and recovered the identity, the recover phrase should not …

fix: add whitespace after tapping the suggestion text

---

e2e/identityManipulation.spec.js
e2e/testIDs.js
specs/util/identitiesUtils.spec.js
src/components/CompatibleCard.js
src/components/ScreenHeading.js
src/constants.js
src/screens/AccountNetworkChooser.js
src/screens/PathDetails.js
src/screens/PathsList.js
src/stores/AccountsStore.js
src/util/alertUtils.js
src/util/identitiesUtils.js
src/util/navigationHelpers.js

Extract Identity root account and  network root account from the clickable heading.
Now Identity root account is in the custom network account list, and network root account is in the correspond network account list.
|identity root account | network root account | network chooser list
|---|---|---|
|<img width="328" alt="Screen Shot 2020-01-20 at 13 20 50" src="https://user-images.githubusercontent.com/6014309/72703972-3c3b3a80-3b92-11ea-9ccc-6fd999a887c7.png">|<img width="329" alt="Screen Shot 2020-01-20 at 13 20 07" src="https://user-images.githubusercontent.com/6014309/72703990-49f0c000-3b92-11ea-9fc6-c453c934792d.png">|<img width="347" alt="Screen Shot 2020-01-20 at 13 19 59" src="https://user-images.githubusercontent.com/6014309/72704003-5412be80-3b92-11ea-8571-3c813af86fa8.png">|
* …

refactor: identity root account and network root account

---

package.json

This repo's dependencies currently use [older versions](https://github.com/paritytech/parity-signer/blob/97651dcc2f78027aa83c3dc7834f6941e084c8a7/yarn.lock#L5138) of kind-of which have a possibly exploitable vulnerability ([original issue](https://github.com/jonschlinkert/kind-of/issues/30), [PR](https://github.com/jonschlinkert/kind-of/pull/31)).

fix: Use kind-of >=6.0.3 everywhere

---

src/screens/PathDetails.js

After delete an account with custom path, it should redirect to the custom paths list, but not the list of the fallback network like Kusama.
Reproduce: 
choose any account with custom path (it has Kusama network affliation) -> delete it -> Now it is navigate to kusama path list.
Screen recording (Check the screen after input the PIN): 
| before | after |
|---|---|
|![out mp4](https://user-images.githubusercontent.com/6014309/74146525-8cda0c80-4c01-11ea-9cc4-55308c88dd59.gif)|![out mp4](https://user-images.githubusercontent.com/6014309/74146588-aed38f00-4c01-11ea-91ef-77700d3d2e26.gif)|

fix: redirection for account with custom path

---

android/app/build.gradle

Should not use debug signing schema for release version build.

build: fix release config for android

---

src/components/PathCard.tsx
src/constants/networkSpecs.ts
src/screens/AccountNetworkChooser.tsx
src/screens/PathDerivation.tsx
src/screens/PathDetails.tsx
src/screens/PathsList.tsx
src/stores/AccountsStore.ts
src/types/networkSpecsTypes.ts
src/utils/account.ts
src/utils/identitiesUtils.ts
test/unit/specs/util/identitiesUtils.spec.ts

This PR refactor the way to categorize accounts under their network, is the extend of #574, it address #573 , more specifically:
1. The network created by custom path should be categorized into their own network.
2. Now we support user created any path with any network, though it is not encouraged. For example, user should be able to create account under Westend network with path `//kusama//any_custom_path` and explicitly pointing that using westend network.
also rename "Custom Network" back to "Unknown Network", since now only account created in the previous version without appointing any network is listed here. (They currently use Kusama, but the hint text ask them to recreate it)
Previously:
| Kusama| Custom Network |
|----|----|
|Only contain account path prefixed with …

refactor: regroup the paths into their own network.

---

src/components/IdentitiesSwitch.tsx
src/utils/seedRefHooks.ts

closes #593 
After fix:
@sjeohp I have also included a minor fix for the signature of Substrate sign function

fix: identities switch bottom shadow blocks button

---

package.json
src/modules/main/components/NetworkSelector.tsx

closes #542 
As `BackHandler` only existed in andriod, and on iOS swipe back won't lead user to quit app.
So this PR only focus on Android.
The test result should be the same as descripted in the issue's expected screen record.

fix: prevent back on network choser android

---

src/modules/sign/screens/QrScanner.tsx
test/e2e/injections.ts

Actually this pr add the missing commits for #603 
After scanning and in the pin input screen, is user press back, the next scan will not triggered if qr is not changed, this prevent the error
Also add the timeout for e2e scan test, which enable the screen to do the cleanup and transition with correct workflow

fix: scanning block and e2e

---

src/components/CompatibleCard.tsx
src/constants/networkSpecs.ts
src/modules/main/components/NetworkSelector.tsx
src/modules/sign/screens/SignedMessage.tsx
src/modules/sign/screens/SignedTx.tsx
src/modules/sign/utils.ts
src/utils/identitiesUtils.ts
test/unit/specs/util/identitiesUtils.spec.ts

fix #606 
This PR :
1. refactor the `getPathsWithSubstrateNetworkKey` in PathsList and `getExistedNetworkKeys` in NetworksList.
2. Add Unit test to check missing account.
2. use FlatList for networks, for better performances.
3. Strict checking for SignedTx and SignedMessage screen to prevent crash.

fix: missing accounts on v4.2

---

android/app/build.gradle
ios/NativeSigner/Info.plist
package.json
src/stores/SeedRefStore.tsx

When clean the seed references, does not call the `setSeedRefs` function, which leads that the context do not update.
Also bump the version to v4.2.2

fix: seed reference destroy bug

---

android/app/build.gradle
ios/NativeSigner/Info.plist
package.json
src/modules/sign/screens/SignedMessage.tsx
src/modules/sign/screens/SignedTx.tsx
test/unit/specs/util/decoders.spec.ts
yarn.lock

This PR makes SIgner fit for [txVersion](https://github.com/paritytech/substrate/pull/5979) update on Substrate.
Specifically:
1. In order not to block the upgrade of Kusama, temporary remove the `PayloadDetailCard`. 
2. Update the Polkadot.js related pacakges
3. bump the version

fix: fit for the txVersion update

---

src/screens/IdentityNew.tsx

This is the fix according to user report:
> I had some issues yesterday with naming new identities. I could only type one letter at a time and then had to click again each time on the text field. it looked like the spelling/word recogintion didn't properly work. it was an iphone 5se installed fresh yesterday. 
Though I can't reproduce on my devices and simulators, but I think this line of code maybe lead to the incorrect behavouir.

fix: new identity name input can't be focus

---

src/components/IdentitiesSwitch.tsx

This PR add minor improvement, which do not need to reset currentIdentity before going to legacy account list.

chore: reset current identity in async way

---

src/components/DerivationNetworkSelector.tsx
src/components/PathGroupCard.tsx
src/constants/networkSpecs.ts
src/modules/network/utils.ts
src/utils/db.ts
src/utils/identitiesUtils.ts

close #539 
Currently the KUSAMA_CC2 Network related accounts will be grounped under `Unknown Network`.

fix: remove kusama CC2 Network

---

src/components/AccountCard.tsx
src/components/AccountIcon.tsx
src/components/AccountPrefixedTitle.tsx
src/components/CompatibleCard.tsx
src/components/PathCard.tsx
src/components/Warnings.tsx
src/modules/network/utils.ts
src/modules/sign/screens/SignedTx.tsx
src/modules/sign/utils.ts
src/screens/AccountDetails.tsx
src/screens/LegacyAccountBackup.tsx
src/stores/AccountsContext.ts
src/stores/ScannerContext.ts
src/utils/account.ts
src/utils/identitiesUtils.ts

This PR:
1. prepare for the network management, fix unknown network display error.
2. closes #625 , now user could see the identity name when they sign a transaction/message
|substrate|ethereum|
|---|---|
|![Simulator Screen Shot - iPhone 8 - 2020-08-12 at 12 03 31](https://user-images.githubusercontent.com/6014309/90019818-38e2da00-dcaf-11ea-8fa9-4e07c7859323.png)|![Simulator Screen Shot - iPhone 8 - 2020-08-12 at 12 10 23](https://user-images.githubusercontent.com/6014309/90019842-4009e800-dcaf-11ea-9cf1-acd990630aa4.png)|

fix: erros on unknown network. show Identity on SignedTx/SignedMessage screen

---

android/app/build.gradle
ios/NativeSigner.xcodeproj/project.pbxproj
ios/NativeSigner/Info.plist
ios/Podfile.lock
package.json
yarn.lock

This prebuilt ARM32 does not works well, this PR use the fallback prebuilt Android ARM32 library as tempororay solution.
This PR also bump the version to 4.5.0

fix: update android arm32 rust library and bump version

---

src/modules/sign/strings.ts
src/utils/decoders.ts

When parsing the random string, it is sometimes is parsed as a multi frames qr code, this walkaround prevent this behavior somehow.

chore: improve parsing message error

---

.eslintrc.js
src/modules/sign/components/PayloadDetailsCard.tsx
test/e2e/setup.ts

This PR closes #739 and many similar issues, but makes thing slightly uglier.

fix: Transaction parser

---

.gitlab-ci.yml
docker/Dockerfile
scripts/build-release.sh
scripts/build.sh
scripts/init.sh

Adds a release-build of the android app and produces a self-signed APK that can be fetched from Gitlab

ci: Rework Gitlab

---

.gitlab-ci.yml

This PR add pipeline functionality to retry CI jobs twice in case if it failed due to following reasons: 
```
- runner_system_failure
- unknown_failure
- api_failure
```

ci: Add retry failed CI jobs twice

---

.gitlab-ci.yml
docker/Dockerfile
scripts/build-release.sh
scripts/build.sh
scripts/init.sh
scripts/sign_android.sh
scripts/sign_metadata.sh

This adds/fixes Gitlab building of the android component of the project. It creates two CI jobs; one that just builds the project (not tremendously useful) and another that builds it *and* signs it, producing an APK that can actually be installed. The latter only runs on merging with master, due to needing to access protected variables in Gitlab

ci: Revive android building

---

CODEOWNERS

This PR adds CODEOWNERS file to the repository.
It is needed to increase awareness of the developers about related code changes.
Currently it adds CI team related stuff. But feel free to propose additions or changes to it either within this PR or later.

ci: Add `CODEOWNERS` file

---

ios/NativeSigner/Models/Navigator.swift
ios/NativeSigner/Models/RustNative.swift
ios/NativeSigner/Models/Seeds.swift
ios/NativeSigner/Screens/SettingsScreen.swift

Fix bug with multiple seed creation.
Code is not readable at all; just test it - create seeds with similar and different phrases, one should be possible, another not.
Also wipe signer on init once more - just to prevent legacy stuff from coming up after update.
And prevent NavigationError event from appearing in Settings.

fix: ios: seed collision check fix

---

rust/definitions/src/error.rs
rust/generate_message/address_book
rust/generate_message/src/interpret_specs.rs

When network returns units+decimals in array of length 1, we should accept it (if it matches with metadata definitions), because it is not ambiguous.
Also generate_message has now result of attempt to generate Signer updates for everything found on polkadot-js pages.

fix: metadata import unit in vector

---

rust/Cargo.lock
rust/qrcode_rtx/Cargo.toml
rust/qrcode_rtx/src/lib.rs

The `apng-encode`  looks unmantained and also brings in `failure` which is also unmantained.
```
Crate:         failure
Version:       0.1.8
Warning:       unmaintained
Title:         failure is officially deprecated/unmaintained
Date:          2020-05-02
ID:            RUSTSEC-2020-0036
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0036
Dependency tree:
failure 0.1.8
└── apng-encoder 0.3.0
└── qrcode_rtx 0.1.0
└── generate_message 0.1.0
└── signer 0.1.0
```
`png` crate looks more alive, being benchmarked and fuzz-tested and has a far wider user base.

fix: replace apng-encoder with png

---

ios/NativeSigner/Components/CameraView.swift

Keep scan screen running on ios while multiframe is scanned

fix: ios: stay awake on scan

---

rust/db_handling/src/helpers.rs
rust/definitions/src/error_signer.rs
rust/definitions/src/test_all_errors_signer.rs
rust/transaction_parsing/src/holds.rs
rust/transaction_parsing/src/load_metadata.rs

When processing `load_metadata` update, Signer must check the network name.

fix: load_metadata update: additional name check

---

rust/db_handling/src/helpers.rs
rust/db_handling/src/identities.rs
rust/db_handling/src/tests.rs
rust/definitions/src/error_signer.rs
rust/definitions/src/history.rs
rust/definitions/src/keyring.rs
rust/definitions/src/metadata.rs
rust/definitions/src/test_all_errors_signer.rs
rust/signer/src/signer.udl
rust/transaction_parsing/src/add_specs.rs
rust/transaction_parsing/src/load_metadata.rs
rust/transaction_parsing/src/tests.rs

Name must be checked in `add_specs` update across all encryptions.

fix: check same name in add_specs, few nits

---

rust/db_handling/src/identities.rs
rust/definitions/src/error.rs
rust/definitions/src/error_active.rs
rust/definitions/src/error_signer.rs
rust/definitions/src/test_all_errors_signer.rs
rust/navigator/src/tests.rs

Forbid empty seed in `create_address`, on Rust side. In Substrate empty seed is interpreted as default Alice seed ("bottom drive obey ...").
Also block empty seed name (already must be unaccessible from the user interface).

fix: forbid empty seed

---

.github/workflows/docs.yml

- places generating user-docs after rustdocs are built, so it's possible to check the links between them
- publishes user-docs to https://paritytech.github.io/parity-signer/user-docs/
- publishes rustdocs to i.e. https://paritytech.github.io/parity-signer/rustdocs/constants/index.html (it's better to choose an initial page and place an index.html like [this](https://github.com/paritytech/substrate/blob/master/scripts/ci/gitlab/pipeline/build.yml#L157))
- empties `gh-pages` branch after every deploy (on master) with `force_orphan: true`

ci: restructure the docs pipeline

---

.github/workflows/docs.yml

Previously I tried to put rustdocs into an `mdbook`-generated `./docs/book/html` dir. This was done to have user-docs in the root https://paritytech.github.io/parity-signer and rustdocs in https://paritytech.github.io/parity-signer/rustdocs.
But [apparently](https://github.com/rust-lang/mdBook/issues/218) `mdbook` doesn't have a flag to skip cleaning the book output-dir. Also, I couldn't find if it's possible to mention this rustdocs dir in the `SUMMARY.md` or `book.toml`.
UPD: thanks to https://users.rust-lang.org/t/how-to-create-link-between-rustdoc-and-mdbook/50189/4
It leads me to the [doc](https://rust-lang.github.io/mdBook/guide/creating.html#source-files) dimly saying that:
> All other files in the `src` directory will be included in the output. So if you have images or other …

ci: workaround mdbook bug

---

rust/generate_message/src/lib.rs

[Metadata portal](https://github.com/paritytech/metadata-portal) would benefit a lot by using `meta_fetch`, `specs_agnostic` and `MetaFetched` from `generate_message::helpers` module.

chore: make generate_message helpers public

---

docs/book.toml

* it is flaky (apple.com and others ban CI from time to time)
* not buildable while on the airplane.

fix: do not follow web links in mdbook

---

README.md

This PR updates build documentation for iOS to include tooling instructions
- add instructions regarding one-time brew dependencies
- add M1-specific instructions

docs: update iOS build docs to account for tooling

---

ios/NativeSigner.xcodeproj/project.pbxproj

This PR fixes issues with SwiftUI "Preview Content" mode that enables easy UI prototyping and also some build issues that started happening after changing the branch or multiple builds, after changes introduced by: https://github.com/paritytech/parity-signer/pull/1229
- add checks for all Build Phases that potentially modify files during indexing
- add checks for *.udl file processing Build Rules to avoid file generation during indexing or Preview Content
Opened issue: https://github.com/mozilla/uniffi-rs/issues/1315
This is XCode 13+ related issue, found solution while googling this out on one of [the issues within Cuckoo Github page](https://github.com/Brightify/Cuckoo/issues/400) (tool that autogenerates files for Swift)

chore: fix build issues and Preview Content

---

rust/db_handling/src/interface_signer.rs
rust/db_handling/tests/tests.rs
rust/definitions/src/navigation.rs
rust/navigator/src/tests.rs
rust/signer/src/signer.udl

Provide UI a number of derived keys
Add `derived_keys_count` field to `SeedNameCard` struct

chore: add derived_keys_count to SeedNameCard

---

ios/NativeSigner/Core/Keychain/KeychainAccessAdapter.swift

This PR fixes issue introduced in refactor: https://github.com/paritytech/parity-signer/pull/1239
This bug required user to provide passcode twice when adding new keys, as `authenticated` was incorrectly set to `false`
I basically messed out on bool logic check when refactoring 
Unfortunately at this stage I'm unable to provide unit tests for this change without further refactor to how we interact with Keychain 🙏🏻 
https://user-images.githubusercontent.com/1955364/187914710-a40ddd74-1c1e-48bf-ae70-3b9aa3be74c2.MP4
https://user-images.githubusercontent.com/1955364/187913895-ec9ecd42-80c9-40e4-95d4-2b40c14363c2.MP4

fix: don't trigger second authorization request when checking for seed collision

---

docs/src/tutorials/Add-New-Network.md
rust/generate_message/address_book
rust/generate_message/src/derivations.rs
rust/generate_message/src/helpers.rs
rust/generate_message/src/interpret_specs.rs
rust/generate_message/src/lib.rs
rust/generate_message/src/load.rs
rust/generate_message/src/parser.rs
rust/generate_message/src/remove.rs
rust/generate_message/src/specs.rs

Fixing a pile of out of date documentation around arguments and commands
This PR aims to address issue: #1253 
- add_specs -> add-specs
- load_metadata -> load-metadata
- load_types -> load-types
- Fix add-spec encryption flag docs
- Fix title flag on add-spec and derivations
- Fix cargo run remove title
- Lots of places where it had one `-` and needed `--`
- Update make goal documentation
- Replace references to the old msgtype with msg 
- Update `--token` with `--token-decimals` and `--token-unit`
- Update the add new network tutorial
- I tried to make the commits do one thing at a time. That might help reviewing if you want to take it commit by commit
- On some of these there is the option of going back to `_`. aka the docs were right and the code was wrong.
- I tried to leave payloads …

docs: Fix documentation around commands and arguments

---

rust/db_handling/src/identities.rs
rust/definitions/Cargo.toml
rust/definitions/src/keyring.rs
rust/definitions/src/lib.rs
rust/definitions/src/qr_transfers.rs
rust/generate_message/src/parser.rs

Make code reusable for the `metadata-portal`
- fix imports for `active` and `signer` features
- make `Verifier`,  `Signature` and `Sufficient` fields public

chore: make code reusable by metadata-portal

---

android/app/src/main/java/io/parity/signer/components/Authentication.kt
android/app/src/main/java/io/parity/signer/models/SignerDataModel.kt

Removed requirement of strong biometric authentication for new android devices. 
User can now use any authentication that it set on device before unlocking secure storage to get the master key.

fix: Removing requirement of biometric

---

ios/NativeSigner.xcodeproj/project.pbxproj
ios/NativeSigner/Components/Buttons/ActionButton.swift
ios/NativeSigner/Components/Buttons/EmptyButton.swift
ios/NativeSigner/Components/Buttons/PrimaryButton.swift
ios/NativeSigner/Components/Buttons/SecondaryButton.swift
ios/NativeSigner/Design/Animations.swift
ios/NativeSigner/Modals/AddKeySet/AddKeySetModal.swift
ios/NativeSigner/Modals/Alerts/HorizontalActionsBottomModal.swift
ios/NativeSigner/Modals/KeySet/KeyDetailsActionsModal.swift
ios/NativeSigner/Resources/en.lproj/Localizable.strings
ios/NativeSigner/Screens/KeyDetails/KeyDetailsView.swift

This PR adds redesign confirmation when choosing `Delete` action.
It does not cover additional confirmation toast, as currently Rust navigation takes user to Logs screen 🤷🏻 
I'll issue separate PR with some design component that looks like toast notification and will add ability to trigger multiple Rust actions to properly move user back to `Keys` screen, not to `Logs
- `HorizontalActionsBottomModal` that adds universal bottom sheet with main action and cancel action, customisable via dedicated view model
- addition of `HorizontalActionsBottomModal` as another full screen cover in `KeyDetailsView` to be presented after `Delete`
- small refactor to `ActionButton` styling
- small refactor to chained animation to make it DRY
- adding custom fake calls to Rust, to be able to replicate old …

style: add remove key confirmation bottom sheet

---

ios/NativeSigner/Components/Buttons/ActionSheetButton.swift
ios/NativeSigner/Screens/KeyDetails/KeyDetailsView.swift

This PR fixes issues with non-touchable areas between visible components in some elements of the UI
- add `.contentShape(Rectangle())` in touchable components with `Spacer()`
| Key Details elements | Key Details menu |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/189342610-1281b3b7-18b7-44b4-bf88-8c0e304ddce8.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/189342670-a44496b4-440b-48ee-9ba5-bb0d0551d6a0.png" width="320px">|
| Interactions |
|-|
|<img src="https://user-images.githubusercontent.com/1955364/189342833-7397f8b6-874c-42f0-914d-8d39bded85c8.gif" width="320px">|

fix: fix touch space over Spacer elements within UI components

---

ios/NativeSigner.xcodeproj/project.pbxproj
ios/NativeSigner/Components/Animators/TapAndDelayDismissAnimator.swift
ios/NativeSigner/Components/Modals/Snackbar.swift
ios/NativeSigner/Components/Overlays/BottoEdgeOverlay.swift
ios/NativeSigner/Core/Keychain/SeedsMediator.swift
ios/NativeSigner/Core/Navigation/NavigationCoordinator.swift
ios/NativeSigner/Core/ServiceLocator.swift
ios/NativeSigner/Design/AnimationDuration.swift
ios/NativeSigner/Design/Heights.swift
ios/NativeSigner/Modals/Alerts/HorizontalActionsBottomModal.swift
ios/NativeSigner/Resources/Assets.xcassets/fill_12_solid.colorset/Contents.json
ios/NativeSigner/Resources/en.lproj/Localizable.strings
ios/NativeSigner/Screens/Containers/AuthenticatedScreenContainer.swift
ios/NativeSigner/Screens/KeyDetails/Actions/ForgetKeySetAction.swift
ios/NativeSigner/Screens/KeyDetails/KeyDetailsView.swift
ios/NativeSigner/Screens/KeySetsList/KeySetList.swift
ios/NativeSigner/Screens/ScreenSelector.swift

This PR provides custom `Snackbar` component and necessary additional reusable components that enable animation transitions and others 
- `Snackbar` UI component
- `BottomEdgeOverlay`, `TapAndDelayDismissAnimator` components that can be used with any View to provide bottom edge animation and autodismiss functonality
- set of ViewModifiers to use any of above and snackbar with both mentioned components through `ViewModifier`
- addition of `.bottomSnackbar` to `AuthenticatedScreenContainer`, to present Snackbar from every view over tab bar (or just bottom edge)
Additionally to update `Forget Key Set` flow:
- possibility to chain calls to Rust without UI debounce that's implemented by default to prevent accidental double taps on UI actionable components
- `ForgetKeySetAction` that wraps all …

feat: Snackbar component and finalised Forget Keys flow

---

ios/NativeSigner/Screens/KeyDetails/DerivedKeyRow.swift
ios/NativeSigner/Screens/KeyDetails/KeyDetailsView.swift

Fixing UI issue reported by @tetekinandrey 
| Current | Fix |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/190173685-aaf8020e-3631-4758-81fe-25eb8eb68012.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/190173600-fdb13c01-9383-43b5-addb-1e2bed875735.png" width="320px">|

style: iOS fix spacing and icons color for Key Details screen

---

Gemfile
Gemfile.lock
ios/fastlane/Fastfile

Extension of https://github.com/paritytech/parity-signer/pull/1296
Although my last PR fixed TF flow for me locally, there are mutliple Xcode 14.0 instances on GA (beta + official), so I needed to remove Fastlane Xcode selection as it was defaulting to beta build to rely fully on xcode-select call in initial GA setup.
Below build was triggered and successfully distributed using this branch, this confirming that this works
https://github.com/paritytech/parity-signer/actions/runs/3081535731

chore: remove TF version from fastlane to avoid selecting beta build

---

ios/NativeSigner/Resources/en.lproj/Localizable.strings
ios/NativeSigner/Screens/KeySetsList/KeySetList.swift

This PR provides empty state for `Key Set List` screen according to new Figma designs
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/191051824-018200df-d1cb-4013-93d4-22ca9a94271d.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/191051866-05478bc7-a001-4696-868d-dece76e7613b.png" width="320px">|
| Dark |
|-|
|<img src="https://user-images.githubusercontent.com/1955364/191051987-2ab3513b-10ae-4ca4-a39c-d2eebe1671b9.gif" width="320px">|

feat: iOS empty state for Key Set List

---

android/generate_database.sh

should copy content of cold_release folder, not the folder itself to coply with path we are searching.

fix: android db script 

---

CODEOWNERS

Currently I cannot deselect Andrey from review changes, that don't include any UI.

chore: don't force design review for non UI

---

rust/db_handling/src/helpers.rs
rust/db_handling/src/identities.rs
rust/defaults/src/lib.rs
rust/navigator/src/screens.rs
rust/parser/src/decoding_older.rs
rust/parser/src/decoding_sci.rs
rust/transaction_parsing/src/check_signature.rs

A new rustc version `1.64.0` has new `clippy` lints. This fixes them.

fix: fix clippy on new stable

---

ios/NativeSigner/Core/Keychain/SeedsMediator.swift
ios/NativeSigner/Screens/KeyDetails/KeyDetailsView.swift
ios/NativeSigner/Screens/PublicKey/KeyDetailsPublicKeyView.swift
ios/NativeSigner/Screens/ScreenSelector.swift

This PR fixes flow on `Backup Modal` when user was or is connected to network
I'll replace system alert with custom one, once it's done and available
| Example interaction | 
|-|
|<img src="https://user-images.githubusercontent.com/1955364/191984133-dd3c171c-eb0b-42ad-be69-71890408ed24.gif" width="320px">|

fix: ios: add alert for backup modal if network was connected

---

ios/NativeSigner.xcodeproj/project.pbxproj
ios/NativeSigner/Backend/ExportPrivateKeyService.swift
ios/NativeSigner/Previews/PreviewData+Rust.swift
ios/NativeSigner/Screens/KeyDetails/KeyDetailsView.swift
ios/NativeSigner/Screens/PublicKey/KeyDetailsPublicKeyView.swift
ios/NativeSigner/Screens/ScreenSelector.swift

This PR fixes issues with pincode being triggered on views presentation instead just before it was needed.
- I tried to follow proper approach, generating view model on View's instance right before presentation, but as Rust navigation refreshes the view, needed to add `static` references for view models within views for now

fix: ios: ask for pincode only when needed

---

ios/NativeSigner/Core/Navigation/NavigationCoordinator.swift
ios/NativeSigner/Screens/KeyDetails/Actions/ForgetKeySetAction.swift
ios/NativeSigner/Screens/KeyDetails/Actions/ForgetSingleKeyAction.swift
ios/NativeSigner/Screens/KeyDetails/KeyDetailsView.swift
ios/NativeSigner/Screens/PublicKey/KeyDetailsPublicKeyView.swift
ios/NativeSigner/Screens/ScreenSelector.swift

This PR fixes issue introduced by this refactor: https://github.com/paritytech/parity-signer/pull/1333 where I tried to move to use of SwiftUI @EnvironmentObject for `SignerDataModel` and `NavigationCoordinator` which encapsulates Rust navigation.
We still can't use it in non-view components and my replace-all approach triggered crash on forget key actions.
Additionally, in second commit, navigation fix was added when removing single derived key (forgot about that fix I had in stash before)

fix: ios: fix crash on "Forget Key" functionality

---

rust/db_handling/src/identities.rs
rust/navigator/src/navstate.rs

The code unwraps unnecessarily on not found keys. Also some parts of the
UI use public keys for addressing instead of addresses. Untils the addressing
issue is fixed, support both:
* Search for an Ethereum addr
* Search for public addr
In the future this has to be replaced with typed addresses instead of byte blobs or `String`s.

fix: no panics on not found keys

---

rust/qr_reader_phone/src/process_payload.rs

Fix Qr `block_number`, because `source_block_number` always returns `0`.
This breaks progress bar in metadata-portal
As a workaround, use `encoding_symbol_id` instead.

fix: raptorq block number

---

ios/NativeSigner/Screens/KeyDetails/Views/KeyDetails+SelectionOverlay.swift
ios/NativeSigner/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift
ios/NativeSigner/Screens/KeyDetails/Views/KeyDetailsView.swift
ios/NativeSigner/Screens/ScreenSelector.swift

Refactor around `@StateObject viewModel: ViewModel` for `KeyDetailsView` broke not refactored network selection, this PR fixes this by moving changeable view model for given network back to view level
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/199731686-71a4a7fd-9012-4330-895d-29f7f1037673.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/199731659-b82eb04c-bb5f-4d12-86d0-2e67791c7f37.gif" width="320px">|

fix: ios: fix Network Selection on Key Details broken by refactor for keys export

---

rust/db_handling/src/identities.rs
rust/db_handling/src/interface_signer.rs
rust/db_handling/tests/tests.rs
rust/definitions/src/helpers.rs
rust/generate_message/src/remove.rs
rust/navigator/src/tests.rs
rust/parser/src/cards.rs
rust/parser/src/tests.rs
rust/transaction_parsing/src/cards.rs
rust/transaction_signing/src/tests.rs

Fix `clippy` on new rust stable `1.65`.

fix: clippy on rust 1.65

---

ios/NativeSigner/Core/Connectivity/ConnectivityMediator.swift
ios/NativeSigner/Core/Database/DatabaseMediator.swift
ios/NativeSigner/Core/Protocols/FileManagingProtocol.swift
ios/NativeSigner/Models/RustNative.swift
ios/NativeSignerTests/Core/Database/DatabaseMediatorTests.swift

This fixes few smaller issues:
- if user opens the app first time in online mode, they can't go pass initial screen, which is fine - but when they run app second time, application will have invalid database state. This is because app was calling `historyDeviceWasOnline` when device was online and before first call to `initNavigation` was called
- in above scenario user would see old seed names from keychain even if app was deleted, because app was calling `updateSeedNames` with seed names from old keychain - this is addressed by wiping keychain on first install
- also minor semantix when to comes to database path is fixed, we shouldn't use `NSHomeDirectory` if in some places we use `fileManager.url(for: .documentDirectory, in: .userDomainMask)` as these could be different in some iOS …

fix: iOS: Don't send calls to database before initialisation and delete all keychain items on first app run

---

android/src/main/java/io/parity/signer/MainActivity.kt

For example when dark mode is enabled we don't need to ask for password again - viewmodel is already initialized

feat: android should init viewmodel only when new activity is created

---

ios/NativeSigner/Components/Modals/Snackbar.swift
ios/NativeSigner/Design/Heights.swift

Currently Snackbar content is limited to single line, this change allows it to differ in height between 56-72pt and allow to accommodate  1-3 lines

style: iOS: allow for multiline snackbar

---

ios/NativeSigner/Components/Deprecated/Buttons.swift
ios/NativeSigner/Modals/Deprecated/NewSeedBackupModal.swift

After removing old color schemes, there are some issues with new colors used that lead to broken UI elements, this PR addresses that
- refactor old button style calculation
- fix seed phrase background for new phrase

fix: iOS: fix updated styles for old screens using new design color system

---

ios/NativeSigner/Cards/AddressCard.swift
ios/NativeSigner/Components/Rows/DerivedKeyOverviewRow.swift
ios/NativeSigner/Extensions/Models/Address+DisplayablePath.swift
ios/NativeSigner/Modals/ExportKeys/ExportMultipleKeysModal.swift
ios/NativeSigner/Resources/en.lproj/Localizable.strings
ios/NativeSigner/Screens/EnterPasswordModal.swift
ios/NativeSigner/Screens/KeyDetails/Models/KeyDetailsDataModel.swift
ios/NativeSigner/Screens/KeyDetails/Views/DerivedKeyRow.swift
ios/NativeSigner/Screens/KeySetsList/KeySetListViewModelBuilder.swift
ios/NativeSignerTests/Screens/KeySetList/KeySetListViewModelBuilderTests.swift

Present all passworded paths as `///****<lock_icon>` in unified way
Additionally small fix for value filtering on Export Key Set modal

fix: iOS: Present passworded paths in unified way and fix list display in Export Key Sets

---

.github/workflows/actions.yml
rust/db_handling/tests/tests.rs
rust/definitions/src/metadata.rs
rust/definitions/src/qr_transfers.rs
rust/generate_message/src/derivations.rs
rust/generate_message/src/make_message.rs
rust/generate_message/src/parser.rs
rust/generate_message/src/show.rs
rust/navigator/src/lib.rs
rust/navigator/src/tests.rs
rust/qr_reader_pc/src/lib.rs
rust/qr_reader_pc/tests/integration_test.rs
rust/qr_reader_phone/src/lib.rs
rust/qrcode_rtx/src/lib.rs

fix: clippy on rust 1.66

---

ios/NativeSigner/Components/Modals/FullScreenRoundedModal.swift
ios/NativeSigner/Modals/Alerts/HorizontalActionsBottomModal.swift
ios/NativeSigner/Modals/Alerts/VerticalActionsBottomModal.swift
ios/NativeSigner/Modals/Backup/BackupModal.swift
ios/NativeSigner/Modals/ExportPrivateKey/ExportPrivateKeyModal.swift

For devices without `Home` button, fullscreen modals have additional safe area insets that weren't taken into account. This PR fixes that
- add ability to `FullScreenModal` to include different behaviour to accommodate for bottom insets
- add proper settings for calculating bottom insets based on modal type
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/209632488-35cfff13-fb95-43b8-a9bd-6e6effd57cb5.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/209632442-a05676ae-45c7-4cd2-86ba-471521ca6525.png" width="320px">|
|<img src="https://user-images.githubusercontent.com/1955364/209632493-0981f85c-bcf6-4589-b861-812b13886b37.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/209632453-f1936066-e1f …

fix: iOS: bottom safe insets on devices without home button

---

ios/NativeSigner/Screens/KeySetsList/KeySetList.swift

Simple fix for updated background colour on Key Sets, to go over safe area insets on devices with notch
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/209763720-65a1c3a1-b185-450a-906e-53555af51b2c.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/209763746-7e297334-0b3b-4d41-8c4d-85d0cd14ba81.png" width="320px">|

fix: iOS: background on Key Sets on devices with notch

---

ios/NativeSigner/Modals/KeySet/PublicKeyActionsModal.swift

Remove options that are not currently used in Public Key Details
| After change |
|-|
|<img src="https://user-images.githubusercontent.com/1955364/209897723-ffd250b3-da06-4af0-97b5-8b0dd2950121.png" width="320px">|

feat: iOS: hide actions for Public Key Details

---

ios/NativeSigner/Models/RustNative.swift
ios/NativeSigner/Screens/LandingView.swift

Currently when onboarding and having any connectivity, user won't be taken to next screen, but also won't see any message regarding the issue.
This PR introduces temporary solution to present new UI on top of old landing page
- move dead code path from old state manager class directly to landing page
- present new UI when connectivity is detected during onboarding
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/209898807-501627c0-2a3c-42a1-a130-152e539b20c5.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/209898645-c6a102d4-3132-41b1-91da-450fe1830990.gif" width="320px">|

feat: iOS: show informative alert when not disconnected completely during onboarding

---

ios/NativeSigner/Modals/KeySet/KeyDetailsActionsModal.swift

Hide "Derive New Key" that was supposed to be N+1 option in action menu
| After the change |
|-|
|<img src="https://user-images.githubusercontent.com/1955364/209900585-43d32c69-8599-4e30-b0bc-d4a159859d85.png" width="320px">|

feat: iOS: Hide Derive New Key from action menu

---

ios/NativeSigner/Modals/Deprecated/NewSeedBackupModal.swift
ios/NativeSigner/Screens/RecoverSeedPhrase.swift

This option won't be available in new designs, so we should already remove it to allow backend to simplify Rust logic and make sure root is always available
- remove root key checkbox from Add Key Set
- remove root key checkbox from Recover Key Set
- fix font color on Recover screen
- make "Next" button always visible on Recover screen

feat: iOS: hide option to not create root key when adding / restoring key set

---

.gitignore

These paths were updated in https://github.com/paritytech/parity-signer/pull/1067 but the gitignore wasn't.

fix: gitignore temporary signing files

---

android/build.gradle

feat: target android NDK api we are actually using

---

android/src/main/java/io/parity/signer/screens/scan/transaction/TransactionsScreenFull.kt

move rust out of transaction so we can navigate to last navbar action when user leaves camera in 1 go

fix: android adjust android to rust state machine

---

android/src/main/java/io/parity/signer/models/Navigation.kt

Just show toast but don't crash when unneccessary

feat: make android not crash when private key exported for passworded keys

---

ios/NativeSigner/Screens/DerivedKey/Subviews/DerivationPathNameView.swift

Fix password validation if there are multiple occurrences of "///" within path
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/212609945-93d53c88-bb26-4fa0-9656-bfa7baee306f.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/212609961-5900fe77-45c5-407e-b4c0-d166f7e47400.png" width="320px">|
| |<img src="https://user-images.githubusercontent.com/1955364/212610011-a8f4bc37-7156-47bd-b2a2-e12e647616f0.png" width="320px">|

fix: iOS: correct valdiation for passworded path

---

ios/NativeSigner/Screens/Scan/EnterBananaSplitPasswordModal.swift

Fix navigation calls in Banana Split to allow `goForward` to recover keys

fix: ios: fix navigation during banana split

---

ios/NativeSigner/Core/Keychain/SeedsMediator.swift
ios/NativeSigner/Modifiers/SecuredTextField.swift
ios/NativeSigner/Resources/en.lproj/Localizable.strings
ios/NativeSigner/Screens/Scan/EnterBananaSplitPasswordModal.swift

This PR fixes:
- ability to trigger seed recovery by tapping "return" on keyboard for password textfield when seed name textfield is empty
- additional check and error if somehow keychain operation would fail (or somehow seed name is still empty)
- conditional logic as Rust navigation expects different steps depending on whether we already have at least 1 key set or not (old app was expanding modal menu if there are no Key Sets, hence difference in navigation)

fix: ios: Banana Split fixes - avoiding empty seed name and conditional navigation based on number of seeds

---

ios/NativeSigner/Components/Modals/Snackbar.swift

Sometimes some buttons required double touch to work - it turns out that Snackbar background overlay sometimes still holds tap gesture handler, hence tap mechanism was behaving weird, this small PR fixes this

fix: ios: fix issue with touch not being received sometimes in main view contexts

---

rust/Cargo.lock
rust/parser/Cargo.toml

Use `subxt` from crates.io, not from git.

fix: remove git depencency on subxt

---

ios/NativeSigner/Core/Keychain/SeedsMediator.swift
ios/NativeSigner/Models/RustNative.swift

On iOS after recent changes we were calling `update_seed_names` before `init_navigation` thus resulting in failure and setting authentication status to `false` and triggering another passcode screen, this PR fixes that.

fix: ios: fix initial calls to Rust hierarchy

---

rust/db_handling/src/identities.rs
rust/db_handling/tests/tests.rs
rust/navigator/src/tests.rs
rust/transaction_signing/src/tests.rs

It would make sense to expose the root key on each known network instead
of creating derivations that may not even be used.

feat: expose root key by default

---

ios/NativeSigner/Screens/Onboarding/Overview/OnboardingOverviewView.swift

This PR fixes scalability of image on onboarding screen
| iPod touch |  |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/216256236-9b452991-39f3-4d22-bfde-32444e7c552b.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/216256244-c4b35606-d20d-43b3-aca6-c12e653d2bc8.png" width="320px">|
|<img src="https://user-images.githubusercontent.com/1955364/216256255-969de57c-c382-4614-bb5e-f0388f022675.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/216256178-5a1946dd-f678-49c7-a06c-7fe7ef700828.png" width="320px">|

fix: ios: Fixed layout for ipod touch on onboarding screen

---

ios/NativeSigner/Modals/Alerts/HorizontalActionsBottomModal.swift
ios/NativeSigner/Modals/Alerts/VerticalActionsBottomModal.swift
ios/NativeSigner/Modals/Backup/BackupModal.swift
ios/NativeSigner/Modals/Errors/ErrorBottomModal.swift
ios/NativeSigner/Modals/ExportKeys/ExportMultipleKeysModal.swift
ios/NativeSigner/Modals/ExportPrivateKey/ExportPrivateKeyModal.swift
ios/NativeSigner/Modals/ExportPrivateKey/ExportPrivateKeyWarningModal.swift
ios/NativeSigner/Modals/KeySet/KeyDetailsActionsModal.swift
ios/NativeSigner/Modals/KeySet/PublicKeyActionsModal.swift
ios/NativeSigner/Modals/NetworkSelection/NetworkSelectionModal.swift
ios/NativeSigner/Screens/DerivedKey/Subviews/ChooseNetworkForKeyView.swift
ios/NativeSigner/Screens/DerivedKey/Subviews/CreateDerivedKeyConfirmationView.swift
ios/NativeSigner/Screens/DerivedKey/Subviews/DerivationMethodsInfoView.swift
ios/NativeSigner/Screens/KeyDetails/Views/RootKeyDetailsModal.swift
ios/NativeSigner/Screens/KeySetsList/AddKeySetModal.swift
ios/NativeSigner/Screens/KeySetsList/KeyListMoreMenuModal.swift
ios/NativeSigner/Screens/Logs/Views/LogNoteModal.swift
ios/NativeSigner/Screens/Logs/Views/LogsMoreActionsModal.swift
ios/NativeSigner/Screens/Scan/EnterBananaSplitPasswordModal.swift
ios/NativeSigner/Screens/Scan/EnterPasswordModal.swift
ios/NativeSigner/Screens/Scan/TransactionDetailsView.swift
ios/NativeSigner/Screens/Scan/TransactionPreview.swift
ios/NativeSigner/Screens/Settings/Subviews/Backup/SettingsBackupModal.swift
ios/NativeSigner/Screens/Settings/Subviews/Networks/NetworkSettingsDetailsActionModal.swift

Currently for modal components, there is a possibility to trigger `dismiss -> presentation` event with multiple touches on SwiftUI components as we don't block it and use `.toggle()` modifier on `Bool` properties that are being updated within animation block - this PR fixes that to not allow for looping those events.

fix: ios: fix multiple touch events on dismiss actions

---

android/src/main/java/io/parity/signer/backend/UniffiInteractor.kt
android/src/main/java/io/parity/signer/bottomsheets/LogComment.kt
android/src/main/java/io/parity/signer/bottomsheets/ManageMetadata.kt
android/src/main/java/io/parity/signer/bottomsheets/NetworkDetailsMenu.kt
android/src/main/java/io/parity/signer/bottomsheets/SelectSeed.kt
android/src/main/java/io/parity/signer/bottomsheets/TypesInfo.kt
android/src/main/java/io/parity/signer/components/panels/BottomBar.kt
android/src/main/java/io/parity/signer/components/panels/TopBar.kt
android/src/main/java/io/parity/signer/components/qrcode/EmptyQrCodeProvider.kt
android/src/main/java/io/parity/signer/dependencygraph/ServiceLocator.kt
android/src/main/java/io/parity/signer/domain/Navigation.kt
android/src/main/java/io/parity/signer/domain/NetworkExposedStateKeeper.kt
android/src/main/java/io/parity/signer/domain/SeedExtensions.kt
android/src/main/java/io/parity/signer/domain/SignerMainViewModel.kt
android/src/main/java/io/parity/signer/domain/storage/SeedStorageOld.kt
android/src/main/java/io/parity/signer/domain/storage/TransactionOld.kt
android/src/main/java/io/parity/signer/screens/createderivation/DerivationCreateViewModel.kt
android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsNavSubgraph.kt
android/src/main/java/io/parity/signer/screens/keysetdetails/export/KeySetDetailsExportService.kt
android/src/main/java/io/parity/signer/screens/keysets/export/KeySetsExportService.kt
android/src/main/java/io/parity/signer/screens/scan/ScanViewModel.kt
android/src/main/java/io/parity/signer/screens/scan/bananasplit/BananaSplitViewModel.kt
android/src/main/java/io/parity/signer/screens/scan/camera/ScanScreen.kt
android/src/main/java/io/parity/signer/screens/scan/importderivations/Extensions.kt
android/src/main/java/io/parity/signer/ui/MainScreensAppFlow.kt
android/src/main/java/io/parity/signer/ui/rustnavigationselectors/ScreenSelectorsNew.kt
android/src/main/java/io/parity/signer/ui/rustnavigationselectors/SignerSelectorsLegacy.kt

On startup avoid telling rust about exposed airgap before rust navigation is initizlied, suspent till that happens.
This happens when app starting with airplane off.
And main viewmodel renamed as previous name probably misleading.

fix: android fix telling rust about airgap breached till rust navigation initizlied

---

ios/NativeSigner/Resources/en.lproj/Localizable.strings
ios/NativeSigner/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift
ios/NativeSigner/Screens/KeyDetails/Views/KeyDetailsView.swift

Empty state for Key Set Details after moving add button to navigation bar
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/217444000-fd5cc3c5-d8b8-4a42-8713-d3f65a32007a.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/217444008-bb076103-a79e-4516-928d-4d957e603308.gif" width="320px">|

feat: ios: new empty state on key set details and updated spacing

---

ios/PolkadotVault/Core/Navigation/NavigationCoordinator.swift
ios/PolkadotVault/Models/Utils.swift
ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/CreateKey/RecoverSeedName.swift
ios/PolkadotVault/Screens/CreateKey/RecoverSeedPhrase.swift

Visual update to copy and design for Recover Seed Phrase
| Examples |  |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/220306391-1b5eeb55-6ff0-41c0-aece-65e3314e70b0.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/220306262-62cd76b7-f622-4e32-954e-bef39e87f451.png" width="320px">|
| Interaction |  |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/220306292-5b57e008-4b02-4726-ac82-f6049f90f8c6.gif" width="320px">| <img src="" width="320px">|

feat: ios: update recover seed screens

---

ios/PolkadotVault/Screens/Settings/SettingsView.swift
ios/PolkadotVault/Screens/Settings/Subviews/Backup/BackupSelectKeyView.swift

This PR aligns connectivity checks between main Backup modal flow and one in settings
| Connectivity on | Connectivity was on |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/220591874-15291a8a-cda7-4d6e-a87c-2edf2bc035ca.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/220591863-c307004c-4ae2-4c56-9256-ffc08916f30a.gif" width="320px">|

feat: ios: connectivity alert when accessing backup from settings list

---

ios/PolkadotVault/Backend/ExportPrivateKeyService.swift
ios/PolkadotVault/Cards/HistoryCardExtended.swift
ios/PolkadotVault/Components/Image/Identicon.swift
ios/PolkadotVault/Components/Image/NetworkIdenticon.swift
ios/PolkadotVault/Components/QRCode/QRCodeAddressFooterView.swift
ios/PolkadotVault/Components/Rows/DerivedKeyOverviewRow.swift
ios/PolkadotVault/Extensions/Models/SignerImage+Helpers.swift
ios/PolkadotVault/Previews/PreviewData+Components.swift
ios/PolkadotVault/Screens/KeyDetails/Models/DerivedKeyRowModel.swift
ios/PolkadotVault/Screens/KeyDetails/Views/DerivedKeyRow.swift
ios/PolkadotVault/Screens/KeySetsList/KeySetListViewModelBuilder.swift
ios/PolkadotVault/Screens/KeySetsList/KeySetRow.swift
ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyViewModel.swift
ios/PolkadotVault/Screens/Scan/Models/TransactionSummaryModels.swift

This PR brings back support for png payloads for identicons
| Moonbeam example |  |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/220600462-68def9d2-7473-4af4-b07b-a18072922f24.png" width="320px">||

fix: ios: png support

---

ios/PolkadotVault/Components/QRCode/QRCodeAddressFooterView.swift
ios/PolkadotVaultTests/Screens/KeySetList/KeySetListViewModelBuilderTests.swift
rust/transaction_parsing/src/lib.rs

If one TX in the bulk is faulty or is not a Tranasction Signing action,
return just it.

fix: do not gobble up errors in bulks

---

android/src/main/java/io/parity/signer/bottomsheets/sufficientcrypto/SufficientCryptoReady.kt
android/src/main/java/io/parity/signer/bottomsheets/sufficientcrypto/SufficientCryptoReadyViewModel.kt
android/src/main/java/io/parity/signer/components/items/KeyDerivedItem.kt
android/src/main/java/io/parity/signer/components/sharedcomponents/KeyCard.kt
android/src/main/java/io/parity/signer/domain/SeedExtensions.kt
android/src/main/java/io/parity/signer/domain/SharedViewModel.kt
android/src/main/java/io/parity/signer/screens/keysetdetails/backup/SeedbBackupItems.kt
android/src/main/res/values/strings.xml

-    fix: #1680 - explicitly wrote getters so kotlin won't create backed fields and use outdated activity or context from shared viewmodel
-   fix: added network logo and empty path placeholder #1680
-   fix: android fix for old screen qr code was not shown fixed #1679
|-|-|
| ![black](https://user-images.githubusercontent.com/11879032/222806748-c263430d-e2a3-489e-bf32-c6b5d6d99dde.png) | ![white](https://user-images.githubusercontent.com/11879032/222806636-cb18018e-6cf8-4c88-a700-45e847b29484.png) |

fix: Android testing fixes 2

---

ios/PolkadotVault/Core/Keychain/SeedsMediator.swift
ios/PolkadotVault/Modals/Errors/ErrorBottomModalViewModel.swift
ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/CreateKey/NewKeySet/CreateKeySetSeedPhraseView.swift
ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetSeedPhraseView.swift
ios/PolkadotVault/Screens/Scan/BananaSplit/EnterBananaSplitPasswordModal.swift

We need some proper error handling for updated seed phrase recovery
- error handling for seed phrase already exists
- error handling for invalid 24 word combination that is not a valid seed phrase 
| Seed Phrase already exists | Seed Phrase is invalid |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/223465934-23ea959a-4d3a-4107-b7e2-8247259b5242.gif" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/223465953-4301f48e-6d26-4ef0-b385-bf253ff38c51.gif" width="320px">|

feat: ios: error handling for seed phrase recovery

---

ios/PolkadotVault/Components/Text/NetworkCapsuleView.swift
ios/PolkadotVault/Modals/NetworkSelection/NetworkSelectionModal.swift
ios/PolkadotVault/Screens/DerivedKey/CreateDerivedKeyView.swift
ios/PolkadotVault/Screens/DerivedKey/Subviews/ChooseNetworkForKeyView.swift
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSelectionSettings.swift
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSettingsDetails.swift

Capitalise network name everywhere, but during network import via qr code to not create confusion about qr code payload
| Network name previews | 
|-|
|<img src="https://user-images.githubusercontent.com/1955364/223667182-85bff874-c10b-4cff-be12-387498ae4f0e.gif" width="320px">|

chore: ios: capitalise network name everywhere but during import

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSettingsDetails.swift

Fix for #1693. On iOS 15 we are unable to properly delete network from Network Details in Settings

fix: ios: unable to delete network 

---

android/src/main/java/io/parity/signer/screens/scan/transaction/TransactionsScreenFull.kt

Added missing parameter for copy to show amount of transaction in the title

fix: Android copy typo 

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Core/Navigation/NavigationCoordinator.swift
ios/PolkadotVault/Screens/Containers/AuthenticatedScreenContainer.swift
ios/PolkadotVault/Screens/Factories/ModalFactory.swift
ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecDetailsView.swift
ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecEnterPasswordModal.swift
ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecsListView.swift

This PR introduces support for signing network specs and metadata with passworded keys
| Example |  |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/227984765-ea1e521d-2380-49cb-b4a0-333bc39babde.gif" width="320px">|<img src="" width="320px">|
|<img src="https://user-images.githubusercontent.com/1955364/227985236-41ada201-17d3-47b3-8f6a-3a46af091e97.gif" width="320px">|<img src="" width="320px">|
|<img src="https://user-images.githubusercontent.com/1955364/227985283-93987309-62f2-4fe3-a3b1-d1452d711c54.gif" width="320px">|<img src="" width="320px">|

feat: ios: support enter password modal flow for signing network specs / metadata

---

android/build.gradle
android/src/main/java/io/parity/signer/components/AutosizeText.kt
android/src/main/java/io/parity/signer/components/Networklabel.kt
android/src/main/java/io/parity/signer/components/networkicon/NetworkIcon.kt
android/src/main/java/io/parity/signer/domain/UnifiiStubs.kt
android/src/main/java/io/parity/signer/screens/scan/ScanNavSubgraph.kt
android/src/main/java/io/parity/signer/screens/scan/transaction/TransactionsScreenFull.kt
android/src/main/java/io/parity/signer/screens/scan/transaction/transactionElements/TCAddNetwork.kt

fix #1782
- Network logo was broken for empty network logo value - was infinitly scaling up autosize text to fill all space in logo.
- created previews for affected transactions 
- increased version number to do hotfix
note - 60101 was uploaded for testing play store integration script and is skipped version.
I will cherry pick this fix to 6.1.0 branch and release from there.

fix: Android transaction with no logo for network

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Backend/CreateKeySetService.swift
ios/PolkadotVault/Backend/KeyListService.swift
ios/PolkadotVault/Screens/CreateKey/NewKeySet/CreateKeySetSeedPhraseView.swift
ios/PolkadotVault/Screens/CreateKey/NewKeySet/EnterKeySetNameView.swift
ios/PolkadotVault/Screens/Factories/MainScreensFactory.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetailsView.swift
ios/PolkadotVault/Screens/KeySetsList/AddKeySetModal.swift
ios/PolkadotVault/Screens/KeySetsList/KeySetList.swift
ios/PolkadotVault/Screens/Logs/Views/LogDetailsView.swift
ios/PolkadotVault/Screens/Logs/Views/LogsListView.swift
ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift
ios/PolkadotVault/Screens/Scan/CameraView.swift
ios/PolkadotVault/Screens/Settings/SettingsView.swift
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSettingsDetails.swift

This PR introduces native navigation for Create Key Set interaction
- `NavigationView` for create key set interaction
- dedicated services for Key List to fake Rust navigation to get data
- dedicated services for Create Key Set to fake Rust navigation to create key set
| Example |  |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/232495615-2e9b1c99-48a7-4fff-9c58-afcf227d23c5.gif" width="320px">||

feat: ios: create key set native navigation

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Backend/RecoverKeySetService.swift
ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetNameView.swift
ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetSeedPhraseView.swift
ios/PolkadotVault/Screens/DerivedKey/Subviews/DerivationPathNameView.swift
ios/PolkadotVault/Screens/Factories/MainScreensFactory.swift
ios/PolkadotVault/Screens/KeySetsList/AddKeySetModal.swift
ios/PolkadotVault/Screens/KeySetsList/KeySetList.swift

This PR adds native navigation for Restore Key Set flow and services to fake required Rust navigation state machine transitions
| Native navigation |  |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/233019282-ff890403-2ad8-4e76-8470-ab9019aa01eb.gif" width="320px">||

feat: ios: native navigation for Restore Key Set flow

---

ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift

Updated handling for presenting empty derivation path on Public Key Details
| Dark | Light |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/234019446-72263be6-9ed5-4a77-b6d9-56d40c7c2b7d.png" width="320px">|<img src="https://user-images.githubusercontent.com/1955364/234019421-bfbd8e0b-a95a-4fab-9270-a86ad7bf8098.png" width="320px">|

feat: ios: update empty path capitalisation and presentation on Public Key Details

---

android/src/main/java/io/parity/signer/screens/keydetails/KeyDetailsPublicKeyScreen.kt
android/src/main/res/values/strings.xml

Add placeholder for empty derivation path in key details - same as used for small key items during export et.c.
|-|-|
| ![image](https://user-images.githubusercontent.com/11879032/234310085-cd06d162-b8bb-4982-bafd-5ebe83f87656.png) | . |
Note - new figma says "path name" - not sure if we need to change references of path to "path name"

feat: public key empty derivation placeholder added

---

rust/constants/src/lib.rs

update color for rust generated sensitive qr color to pink 300 as per new design
This API is used by android only while there is no platform generation
|-|-|
| ![red_key](https://user-images.githubusercontent.com/11879032/234292557-4a87b1ff-eb73-4d35-bff1-466103a413fe.png) | ![image](https://user-images.githubusercontent.com/11879032/234292249-024f0a8c-15ce-45a5-bcd7-ff13ba539ed4.png) |

feat: update qr code color

---

ios/PolkadotVault/Backend/ManageNetworkDetailsService.swift
ios/PolkadotVault/Core/Data/AppState.swift
ios/PolkadotVault/Screens/Containers/AuthenticatedScreenContainer.swift
ios/PolkadotVault/Screens/Logs/Views/LogEntryView.swift
ios/PolkadotVault/Screens/Settings/SettingsView.swift
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSettingsDetails.swift
ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecDetailsView.swift
ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecEnterPasswordModal.swift
ios/PolkadotVault/Screens/Settings/Subviews/SignSpecs/SignSpecsListView.swift

Full support for native navigation for Sign Sufficient functionality.
Previously going back to list and selecting another key was not working, also cancelling password modal would trigger navigation state lock
| Example |  |
|-|-|
|<img src="https://user-images.githubusercontent.com/1955364/235096754-2eb2eb4c-ef22-4172-8335-39acefc5254b.gif" width="320px">| |

feat: ios: native navigation for Sign Sufficient

---

ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift

This PR aims to address issue: #1850
- fix dependency injection for `SeedsMediator` to use instance from `ServiceLocator` to properly update `seedName` collection

fix: ios: - #1850 Cannot create/import account with the same name after deletion

---

ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSelectionSettings.swift
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSettingsDetails.swift

This PR aims to address issue: #1851 
With native navigation and modal dismissal, we need to update how we pass data to ViewModel initialisation for network details, to not trigger it on remove network confirmation modal

fix: ios: #1851 crash on network deletion

---

ios/PolkadotVault/Components/Modals/FullscreenModal.swift
ios/PolkadotVault/Core/ServiceLocator.swift
ios/PolkadotVault/Screens/DerivedKey/CreateKeyNetworkSelectionView.swift
ios/PolkadotVault/Screens/DerivedKey/Subviews/CreateDerivedKeyConfirmationView.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetailsView.swift
ios/PolkadotVault/Screens/KeySetsList/KeySetList.swift
ios/PolkadotVault/Screens/Logs/Views/LogNoteModal.swift
ios/PolkadotVault/Screens/Logs/Views/LogsListView.swift
ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift
ios/PolkadotVault/Screens/Scan/CameraView.swift
ios/PolkadotVault/Screens/Scan/TransactionPreview.swift
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSelectionSettings.swift
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSettingsDetails.swift

This PR aims to address issue: #1852
After refactor to native navigation, current snackbar presentation approach needed to be revisited - centralised singleton-style modifier applied on main navigation is no more viable and workaround used to attach snackbar view modifier to full screen modal and main nav resulted in doubled snackbars for some of the flows.
Current solution fully prevents from that as snackbar is applied per-screen basis; moreover presentation logic is now moved to screen that actually is presenting snackbar (i.e. when deleting network from Network Details, Network Selection List will handle presentation based on completion closure called from Network Details)

fix: ios: #1852 Present snackbar only in context of current screen, not generic view modifiers

---

rust/navigator/src/tests.rs

small PR to fix new 1.70 clippy regression:
https://github.com/rust-lang/rust-clippy/issues/10870

fix: new clippy warning

---

.github/workflows/actions.yml
.github/workflows/testflight.yml
ios/PolkadotVault/Backend/BananaSplitRecoveryService.swift
ios/PolkadotVault/Backend/CreateDerivedKeyService.swift
ios/PolkadotVault/Backend/NavigationInitialisationService.swift
ios/PolkadotVault/Modals/Errors/ErrorBottomModalViewModel.swift
ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/CreateKey/CreateKeysForNetworks/CreateKeysForNetworksView.swift
ios/PolkadotVault/Screens/CreateKey/NewKeySet/CreateKeySetSeedPhraseView.swift
ios/PolkadotVault/Screens/CreateKey/NewKeySet/EnterKeySetNameView.swift
ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetNameView.swift
ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetSeedPhraseView.swift
ios/PolkadotVault/Screens/KeySetsList/KeySetList.swift
ios/PolkadotVault/Screens/Scan/BananaSplit/EnterBananaSplitPasswordModal.swift
ios/PolkadotVault/Screens/Scan/CameraView.swift
ios/PolkadotVault/StateMediators/OnboardingMediator.swift

This PR provides support for new flow within banana split
- redesign Banana Split recovery
- add specific error handling when creation of derived keys fail after recovery of given key set succeeds
- add create derived keys step after banana split
- minor refactors
| Example |  |
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/da33b127-3044-4aef-b26d-95d0f54e5f56" width="320px">| |
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/eb3e0e6d-712d-4b3a-8415-94911a5df3d9" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/63dcbe47-89f0-4d74-bff1-724f08367881" width="320px">|

feat: ios: banana split derived keys

---

.github/workflows/testflight.yml

Syntax for `base64` has changed slightly for macOS 13 so this aims to fix that

fix: ios: fix testflight deployment on macos 13

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Backend/CreateDerivedKeyService.swift
ios/PolkadotVault/Components/Text/TransparentHelpBox.swift
ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/DerivedKey/CreateKeyNetworkSelectionView.swift
ios/PolkadotVault/Screens/DerivedKey/DerivationPathNameView.swift
ios/PolkadotVault/Screens/DerivedKey/Services/CreateDerivedKeyNameService.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetailsView.swift

This PR adds default derived key name strategy and removes "Allowed on any network" option when creating key
| Primary derived key | "Numeric" derived key |
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/1bec150c-d101-4193-959c-bc94e08c62ff" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/2b685711-c848-4d3b-8897-07b040ca71ff" width="320px">|

feat: ios: default derived key name

---

.github/workflows/actions.yml
.github/workflows/testflight.yml
android/src/main/java/io/parity/signer/screens/createderivation/DerivationPathAnalyzer.kt
android/src/test/java/io/parity/signer/screens/createderivation/DerivationPathAnalyzerTest.kt

Fixes #1914 
android added support for empty path only password derivation path
<!--
|-|-|
| ![image](https://github.com/paritytech/parity-signer/assets/11879032/4eacfef5-e97d-4be9-8770-efeb0d46c6c7) |  |

feat: android support for empty path only password derivation path

---

rust/db_handling/src/identities.rs
rust/db_handling/tests/tests.rs
rust/signer/src/lib.rs
rust/signer/src/signer.udl

Add `try_create_imported_address` function. It should be used to create dynamic derivations addresses.
It works just like `try_create_address`, but marks new address as `was_imported`.

chore: add try_create_imported_address

---

ios/Packages/Blockies/Sources/Blockies/BlockiesConfiguration.swift
ios/Packages/Blockies/Sources/Blockies/BlockiesIdenticonGenerator.swift
ios/Packages/Blockies/Sources/Blockies/BlockiesImageRenderer.swift
ios/Packages/Blockies/Sources/Blockies/PatternGenerator.swift
ios/Packages/Blockies/Sources/Blockies/PseudoRandomColorGenerator.swift
ios/Packages/Blockies/Sources/Blockies/UI/BlockiesIdenticonView.swift
ios/PolkadotVault/Components/BlockiesIdenticonViewPreviews.swift

Fix order of pseudo random generated numbers usage, to generate colors first, image data later on
| Eth blockies rust library | iOS |
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/cbe6131e-a6c3-4b88-b65a-c73fd83f9209" width="450px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/d424217f-e080-4b22-890b-fd526911be91" width="450px">|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/acd816b6-15a6-4da1-a4a2-eb6f97153918" width="450px">| |

fix: ios: fix eth blockies generation

---

ios/Packages/Blockies/Sources/Blockies/BlockiesIdenticonGenerator.swift
ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Backend/CreateDerivedKeyService.swift
ios/PolkadotVault/Backend/DynamicDerivationsService.swift
ios/PolkadotVault/Backend/ExportMultipleKeysService.swift
ios/PolkadotVault/Backend/GetAllNetworksService.swift
ios/PolkadotVault/Backend/ImportDerivedKeysService.swift
ios/PolkadotVault/Backend/KeyDetailsService.swift
ios/PolkadotVault/Backend/KeyListService.swift
ios/PolkadotVault/Backend/LogsService.swift
ios/PolkadotVault/Backend/ServiceError.swift
ios/PolkadotVault/Design/Heights.swift
ios/PolkadotVault/Design/PrimaryFont.swift
ios/PolkadotVault/Extensions/Error+RustDisplayError.swift
ios/PolkadotVault/Modals/Errors/ErrorBottomModalViewModel.swift
ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/DerivedKey/DerivationPathNameView.swift
ios/PolkadotVault/Screens/KeyDetails/Models/DerivedKeyRowModel.swift
ios/PolkadotVault/Screens/KeyDetails/Views/DerivedKeyRow.swift
ios/PolkadotVault/Screens/KeySetsList/KeySetList.swift
ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift
ios/PolkadotVault/Screens/Scan/CameraView.swift
ios/PolkadotVault/Screens/Scan/DynamicDerivations/AddDerivedKeysData.swift
ios/PolkadotVault/Screens/Scan/DynamicDerivations/AddDerivedKeysView.swift
ios/PolkadotVault/Screens/Scan/Services/CameraService.swift
ios/PolkadotVault/Stubs/Stubs+Signer.swift

Support dynamically derived account address for operating in the Nova Spektr application

feat: #1885: iOS: Dynamic Derivations support

---

ios/PolkadotVault/Screens/KeyDetails/ExportKeys/ExportKeysSelectionModal.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetailsView.swift

Update export keys selection design to fit newest one
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/ca2ac2b7-6c7b-45a0-90c0-f18e02c82d1d" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/33cdb605-a697-4015-afac-5dca2defdd84" width="320px">|

feat: ios: update design for export key set to include jdenticon

---

ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetSeedPhraseView.swift

As @Dmitry-Borodin noticed, in old design we were supporting following use case:
- user types in whole word that matches guess word
- user taps "space"
- word is added automatically to recovered seed phrase without a need to tap guess word
This PR brings this functionality back in new redesigned interface
| Example|
|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/2fd80726-897e-4479-9d25-ce3fef4e13c4" width="320px">|

feat: ios: support space tap on seed phrase recovery

---

ios/PolkadotVault/Screens/CreateKey/RecoverKeySet/RecoverKeySetSeedPhraseView.swift

Resolves #2065
| Example |
|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/6cd58e6e-01ef-43b3-a274-173707fe362d" width="320px">|

feat: #2065 ios: Secret recovery field is not tappable

---

ios/PolkadotVault/Components/NavigationBarView.swift
ios/PolkadotVault/Components/TabBar/Builders/TabViewModelBuilder.swift
ios/PolkadotVault/Components/TabBar/TabBarView.swift
ios/PolkadotVault/Components/TabBar/ViewModels/Tab.swift
ios/PolkadotVault/Screens/Containers/AuthenticatedScreenContainer.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetailsView.swift
ios/PolkadotVault/Screens/Settings/SettingsView.swift
ios/PolkadotVaultTests/Components/TabBar/TabViewModelBuilderTests.swift

Another mid-point of updated design to be Key-Details driven.
Next PR will remove tab bar all together
| Example |
|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/18ac972c-0a59-4738-a230-64552d6a6b13" width="320px">|

feat: ios: Move Settings to Key Details

---

.github/workflows/actions.yml
.github/workflows/android-app.yml
.github/workflows/android-release.yml
.github/workflows/rust-clippy.yml
.github/workflows/rust-fmt.yml
.github/workflows/rust-test-android.yml
.github/workflows/rust-test-ios.yml
.github/workflows/testflight.yml

do not use deprecated `actions-rs/toolchain`
https://github.com/actions-rs/toolchain
Use `dtolnay/rust-toolchain` instead

fix: do not use deprecated actions-rs/toolchain

---

android/src/main/java/io/parity/signer/screens/createderivation/DerivationCreateSubgraph.kt
android/src/main/java/io/parity/signer/screens/keydetails/KeyDetailsScreenSubgraph.kt
android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsScreenSubgraph.kt
android/src/main/java/io/parity/signer/screens/keysets/KeySetsListScreenSubgraph.kt
android/src/main/java/io/parity/signer/screens/settings/general/SettingsGeneralNavSubgraph.kt
android/src/main/java/io/parity/signer/screens/settings/logs/logslist/LogsScreenFull.kt
android/src/main/java/io/parity/signer/screens/settings/networks/details/NetworkDetailsSubgraph.kt

There was top left to full screen animation despite animations were disabled when navigating from completely empty composable to something new.
With this changes they appear normally.

fix: fixed appearance of bottom sheets. 

---

android/src/main/java/io/parity/signer/screens/scan/errors/TransactionErrorsModels.kt
ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/Scan/Errors/ErrorDisplayed+LocalizedDescription.swift
ios/PolkadotVault/Screens/Scan/Errors/ErrorDisplayed+TransactionSigning.swift
rust/Cargo.lock
rust/constants/src/lib.rs
rust/db_handling/src/cold_default.rs
rust/db_handling/src/error.rs
rust/db_handling/src/helpers.rs
rust/db_handling/tests/tests.rs
rust/definitions/Cargo.toml
rust/definitions/src/lib.rs
rust/definitions/src/schema_version.rs
rust/signer/src/lib.rs
rust/signer/src/signer.udl

Detect db schema change, prevent app from crashing
- store db version
- expose `check_db_version` to check if app has been upgraded without the re-install.
- added `DbSchemaMismatch` error to catch
Scheme version should be bumped manually every time there is a breaking change on the backend.

chore: store and check db schema version

---

ios/PolkadotVault/PolkadotVaultApp.swift
ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/Containers/MainScreenContainer.swift
ios/PolkadotVault/StateMediators/AppLaunchMediator.swift
ios/PolkadotVault/StateMediators/DatabaseVersionMediator.swift

- Update secret recovery copy
- clean up DB scheme check fallback as discussed in previous PR #2114 
- fixes case where DB scheme check is triggered on fresh install before DB is created 🤦🏻‍♂️ #2114 
- fixes issue with `init_navigation` not being called before DB scheme check for following app runs

feat: ios: db check fixes and keyset recovery screen copy update

---

.github/workflows/actions.yml
ios/fastlane/lanes/lane_tests.rb

CI / CD fails as iPhone 13 was removed, this PR fixes that by running Github Actions workflows on newest sim

fix: ios: update to newest simulator in order to fix CI / CD workflows

---

ios/PolkadotVault/Backend/Services/KeyDetailsActionService.swift
ios/PolkadotVault/Screens/KeyDetails/Views/KeyDetails+ViewModel.swift
ios/PolkadotVault/Screens/PublicKey/KeyDetailsPublicKeyView.swift

Update public key details to show "hot" indicator right after key export
| Example | |
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/ac892845-8b8b-4137-98b7-2be0adc2f217" width="320px">||

feat: ios: update public key details right after key is exported

---

ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/Settings/SettingsItem.swift
ios/PolkadotVault/Screens/Settings/SettingsView.swift

Remove Backup Secret Phrase option from Settings
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/5dc5080b-82ab-4abd-adc1-1900cdeb77cd" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/b315e7c1-6477-46ca-af77-3d529708f4f6" width="320px">|

feat: ios: remove Backup Secret Phrase option from Settings

---

ios/PolkadotVault/Resources/en.lproj/Localizable.strings

As in title, removing last copy reference to Omni Wallet

feat: ios: remove Omni Wallet reference

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Core/Keychain/KeychainAccessAdapter.swift
ios/PolkadotVault/Core/Keychain/KeychainService.swift
ios/PolkadotVault/Core/Keychain/SeedsMediator.swift
ios/PolkadotVault/Resources/en.lproj/Localizable.strings
ios/PolkadotVault/Screens/Containers/AuthenticatedScreenContainer.swift
ios/PolkadotVault/StateMediators/AppLaunchMediator.swift
ios/PolkadotVault/StateMediators/AuthenticatedStateMediator.swift
ios/PolkadotVaultTests/Core/Connectivity/ConnectivityMonitoringAdapterTests.swift
ios/PolkadotVaultTests/Core/Keychain/KeychainAccessAdapterTests.swift
ios/PolkadotVaultTests/Core/Keychain/SeedsMediatorTests.swift

More abstraction around Keychain API usage (wrapper for C-based API) to to be able to mock it and finally cover most crucial logic with unit tests

chore: ios: abstract Keychain Service and add unit tests

---

android/src/main/java/io/parity/signer/screens/keysets/restore/KeysetRecoverViewModel.kt

Workaround for keyboard auto capitalisation while entering recover phrase
When typing phrase with spaces, instead of selecting words from suggestions, after entering space keyboard often capitalizing words as part of autocompletion logic (for example default google keyboard) and it doesn't match seed words, which are not capitalized.
Always lowercase input before consigning adding it into current recovering phrase.
This won't work if capitalization would mean something, but so far it's **always** lowercase, right?

feat: android recover phrase - ignore capitalisation - debatable. 

---

ios/PolkadotVault/Components/Buttons/ActionButton.swift
ios/PolkadotVault/Screens/DerivedKey/CreateKeyNetworkSelectionView.swift

Adding empty state for Create Derived Key flow on network selection
|-|-|
|<img src="https://github.com/paritytech/parity-signer/assets/1955364/f1b4f45d-fc67-4976-9b3e-cbbdc07e8911" width="320px">|<img src="https://github.com/paritytech/parity-signer/assets/1955364/bb98d9f6-933e-4d21-bdce-7772b3fb7d40" width="320px">|

feat: ios: allow for empty state on Create Derived Key

---

.github/workflows/actions.yml
.github/workflows/testflight-prod.yml
.github/workflows/testflight-qa.yml
.gitignore
ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Core/Runtime/RuntimePropertiesProvider.swift
ios/PolkadotVault/Resources/Templates/Sourcery/AutoMockable.stencil
ios/PolkadotVaultTests/Generated/AutoMockable/Scripts/AutoMockableHeader.swift
ios/PolkadotVaultTests/Generated/AutoMockable/Scripts/initial_setup.sh
ios/PolkadotVaultTests/Helpers/Mocks/RuntimePropertiesProvidingMock.swift
ios/sourcery.yml

This PR integrates [Sourcery](https://github.com/krzysztofzablocki/Sourcery) and custom [Stencil](https://github.com/stencilproject/Stencil) template `AutoMockable` (based on [AutoMockable](https://github.com/V8tr/AutoMockable)), in order to automatically generate mocks for protocols with custom annotation `//sourcery: AutoMockable`. Additionally there is custom bash script to create container `AutoMockable+<Letter>.generated.swift` files where generated mocks will be located, based on first letter of protocol name to store them into, to not deal with really big files when there are more mocks (as this is usually an issue, based on my previous experience with tool). This script also adds custom header for file to import any necessary Apple / 3rd party frameworks required by mocks.
This …

chore: ios: Sourcery integration for automatic mocks generation for better unit testing

---

ios/PolkadotVault/Core/Connectivity/ConnectivityMonitoringAdapter.swift
ios/PolkadotVault/Screens/Containers/MainScreenContainer.swift
ios/PolkadotVault/StateMediators/AppLaunchMediator.swift

Fix for outstanding issue described in security report - now each connectivity change is tracked in logs, including case when application would be run on device with broken airgap and then airgap would be restored

fix: ios: track initial connectivity change when application is run and bring back general connectivity logs

---

android/src/main/java/io/parity/signer/domain/backend/UniffiInteractor.kt
android/src/main/java/io/parity/signer/domain/usecases/AllNetworksUseCase.kt
android/src/main/java/io/parity/signer/screens/keysets/create/NewKeysetBackupStepSubgraph.kt
android/src/main/java/io/parity/signer/screens/keysets/create/NewKeysetNameViewModel.kt

show exact error in case of expecting non error instead of null point exception
show proper error message if error in in new derivation flow instead of just going back.

fix: Android reliability

---

android/src/main/java/io/parity/signer/screens/initial/eachstartchecks/osversion/OutdatedOsVersionScreen.kt
android/src/main/java/io/parity/signer/screens/initial/firstTimeOnly/FirstTimeOnly.kt
android/src/main/res/values/strings.xml

Updated copy and files renamed
|-|-|
| ![image](https://github.com/paritytech/parity-signer/assets/11879032/c9e63552-139f-431b-a731-f97f8266214e) | ![image](https://github.com/paritytech/parity-signer/assets/11879032/7ea13827-854d-48b5-a4f5-a0a441756404) |

feat: update update android screen copy

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault.xcodeproj/xcshareddata/xcschemes/PolkadotVault-Dev.xcscheme
ios/PolkadotVault.xcodeproj/xcshareddata/xcschemes/PolkadotVault-QA.xcscheme
ios/PolkadotVault.xcodeproj/xcshareddata/xcschemes/PolkadotVault.xcscheme
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSelectionSettings.swift
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSettingsDetails.swift
ios/PolkadotVault/Screens/Settings/Subviews/Networks/NetworkSettingsDetailsActionModal.swift
ios/PolkadotVaultTests/Models+Generate/MAddressCard+Generate.swift
ios/PolkadotVaultTests/Models+Generate/MKeyDetails+Generate.swift
ios/PolkadotVaultTests/Models+Generate/MSufficientCryptoReady+Generate.swift
ios/PolkadotVaultTests/Screens/Settings/Subview/NetworkSelectionSettings/NetworkSelectionSettingsViewModelTests.swift
ios/PolkadotVaultTests/Screens/Settings/Subview/NetworkSelectionSettings/NetworkSettingDetailsActionModalViewModelTests.swift

Add unit tests for network selection settings and details action modal
- `NetworkSettingsDetailsActionModal.ViewModel` refactor
- Tests for `NetworkSettingsDetailsActionModal.ViewModel`
- Tests for `NetworkSelectionSettingsView.ViewModel`
- Generate methods for most of Rust models

chore: ios: Add unit tests for network selection settings and details action modal

---

android/build.gradle
android/src/main/java/io/parity/signer/PolkadotVaultApp.kt
android/src/main/java/io/parity/signer/domain/Helpers.kt
android/src/main/java/io/parity/signer/domain/MainFlowViewModel.kt
android/src/main/java/io/parity/signer/domain/Navigation.kt
android/src/main/java/io/parity/signer/domain/NavigationLogger.kt
android/src/main/java/io/parity/signer/domain/Utils.kt
android/src/main/java/io/parity/signer/domain/storage/SeedRepository.kt
android/src/main/java/io/parity/signer/domain/storage/SeedStorage.kt
android/src/main/java/io/parity/signer/screens/createderivation/DerivationCreateViewModel.kt
android/src/main/java/io/parity/signer/screens/initial/UnlockScreen.kt
android/src/main/java/io/parity/signer/screens/initial/eachstartchecks/screenlock/SetScreenLockScreen.kt
android/src/main/java/io/parity/signer/screens/keysetdetails/KeySetDetailsViewModel.kt
android/src/main/java/io/parity/signer/screens/keysets/create/NewKeysetNameScreen.kt
android/src/main/java/io/parity/signer/screens/keysets/restore/keysetname/KeysetRecoverNameScreen.kt
android/src/main/java/io/parity/signer/screens/scan/ScanViewModel.kt
android/src/main/java/io/parity/signer/screens/scan/camera/CameraView.kt
android/src/main/java/io/parity/signer/screens/scan/camera/CameraViewModel.kt
android/src/main/java/io/parity/signer/screens/settings/logs/LogsViewModel.kt
android/src/main/java/io/parity/signer/screens/settings/logs/comment/AddLogCommentScreen.kt
android/src/main/java/io/parity/signer/screens/settings/logs/logdetails/LogDetails.kt
android/src/main/java/io/parity/signer/screens/settings/logs/logdetails/LogsDetailsViewModel.kt
android/src/main/java/io/parity/signer/screens/settings/logs/logslist/LogsMenu.kt
android/src/main/java/io/parity/signer/screens/settings/logs/logslist/LogsScreenFull.kt
android/src/main/java/io/parity/signer/screens/settings/networks/signspecs/SignSpecsViewModel.kt
android/src/main/java/io/parity/signer/ui/rootnavigation/MainScreensAppFlow.kt

Do not show logs in release app.
Timber in general allows extra flexibility with managing device logs.

feat: migration togs to Timber so we won't post logs in release app

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Core/JailbreakDetectionPublisher.swift
ios/PolkadotVault/Helpers/ProcessInfoProtocol.swift
ios/PolkadotVault/Helpers/URLOpening.swift
ios/PolkadotVaultTests/Core/JailbreakDetectionPublisherTests.swift
ios/PolkadotVaultTests/Helpers/CancelBagTests.swift

Unit tests for:
- jailbreak detection publisher
- cancel bag
- related refactor and DI improvements

chore: ios: add unit test coverage and relevant refactor for jailbreak detection and cancel bag

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Screens/Settings/Subviews/Backup/BackupSelectKeyView.swift
ios/PolkadotVault/Screens/Settings/Subviews/Backup/SettingsBackupModal.swift
ios/PolkadotVaultTests/Screens/Settings/Subview/Backup/SettingsBackupModalViewModelTests.swift
ios/PolkadotVaultTests/Screens/Settings/Subview/SignSpecs/SignSpecDetailsViewModelTests.swift
ios/PolkadotVaultTests/Screens/Settings/Subview/SignSpecs/SignSpecEnterPasswordModalViewModelTests.swift

As per title, extending unit test coverage

chore: ios: Add unit tests for Sign Specs and Settings Backup Modal

---

.github/workflows/android-release.yml

https://github.com/r0adkll/sign-android-release/issues/84

fix: android for release flow according issue discussion

---

ios/PolkadotVault.xcodeproj/project.pbxproj
ios/PolkadotVault/Screens/DerivedKey/CreateKeyNetworkSelectionView.swift
ios/PolkadotVault/Screens/DerivedKey/DerivationPathNameView.swift
ios/PolkadotVault/Screens/DerivedKey/Services/CreateDerivedKeyNameService.swift
ios/PolkadotVault/Screens/DerivedKey/Subviews/CreateDerivedKeyConfirmationView.swift
ios/PolkadotVaultTests/Models+Generate/DerivationCheck+Generate.swift
ios/PolkadotVaultTests/Models+Generate/MKeyAndNetworkCard+Generate.swift
ios/PolkadotVaultTests/Models+Generate/MKeysNew+Generate.swift
ios/PolkadotVaultTests/Screens/DerivedKey/CreateKeyNetworkSelectionViewModelTests.swift
ios/PolkadotVaultTests/Screens/DerivedKey/DerivationPathNameViewModelTests.swift
ios/PolkadotVaultTests/Screens/DerivedKey/Subviews/AddKeySetUpNetworksStepOneViewModelTests.swift
ios/PolkadotVaultTests/Screens/DerivedKey/Subviews/AddKeySetUpNetworksStepTwoViewModelTests.swift
ios/PolkadotVaultTests/Screens/DerivedKey/Subviews/CreateDerivedKeyConfirmationViewModelTests.swift
ios/PolkadotVaultTests/Screens/DerivedKey/Subviews/DerivationMethodsInfoViewModelTests.swift

Improving test coverage for add derived key flow

chore: ios: Unit tests for derived keys creation

---

android/src/main/java/io/parity/signer/domain/storage/SeedRepository.kt
android/src/main/java/io/parity/signer/domain/storage/SeedStorage.kt
android/src/main/java/io/parity/signer/screens/createderivation/DerivationCreateViewModel.kt
android/src/main/java/io/parity/signer/screens/keydetails/KeyDetailsScreenViewModel.kt
android/src/main/java/io/parity/signer/screens/scan/ScanViewModel.kt
android/src/main/java/io/parity/signer/screens/scan/addnetwork/AddedNetworkViewModel.kt
android/src/main/java/io/parity/signer/screens/scan/importderivations/ImportDerivedKeysRepository.kt
android/src/main/java/io/parity/signer/screens/settings/networks/signspecs/SignSpecsViewModel.kt

decrease probability that seed phrase will be found in memory by manually calling gc() in places where seed phrase no longer in use.
Targets #2269

feat:  Android seed gc

---

rust/Cargo.lock

Those were vulnarable due to cargo-deny check: rustls and h2
Note - those added and removed - transitive dependencies
```
rror[vulnerability]: Degradation of service in h2 servers with CONTINUATION Flood
┌─ /github/workspace/rust/Cargo.lock:148:1
│
148 │ h2 0.3.24 registry+https://github.com/rust-lang/crates.io-index
│ --------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2024-0332
= Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0332
= An attacker can send a flood of CONTINUATION frames, causing `h2` to process them indefinitely.
This results in an increase in CPU usage.
Tokio task budget helps prevent this from a complete denial-of-service, as the server can still
respond to legitimate requests, albeit with increased …
```

fix: updated vulnarable libs

---

.github/workflows/docs.yml
.github/workflows/testflight-prod.yml
.github/workflows/testflight-qa.yml
ios/fastlane/Matchfile
ios/fastlane/lanes/lane_build.rb

This PR:
- fixes doc deploy flow
- change signing for testflight distribution on match
Tested on:
https://appstoreconnect.apple.com/teams/3f6c7763-7365-466f-8419-8af0bda46afe/apps/1218174838/testflight/ios/61a10993-8470-49a2-975a-4e02de354393

fix: deploy workflows

---

android/src/main/res/values/strings.xml

Noticed some odd error messages in the signer, fixed them to be a lot less confusing.
Only updates three of the strings used inside the Android app.

fix: replace non-sense error messages on Android

---

rust/qr_reader_pc/src/lib.rs

We were updating the metadata-portal to be compatible with newer version of opencv and had to realize that the way opencv is used in the rust library of the signer is not backward compatible (see #2429 for details).
As the signer does not make use of the additional flags available in newer opencv, there is actually no reason to not be backwards compatible, so this PR fixes that. 
This has been tested with the latest version of the metadata-portal and the changes proposed in paritytech/metadata-portal#845. The result is that the metadata-portal can be build with older and newer version of opencv without any issues.
Use different opencv binding that assumes default 
@ERussel @stepanLav

fix: opencv backwards compatibility

---

ios/PolkadotVault/Core/JailbreakDetectionPublisher.swift
ios/PolkadotVault/Screens/Containers/AuthenticatedScreenContainer.swift

This PR aims to address issue: #2445
Due to the fact that seeds creation update handler immediately tries to change view hierarchy it conflicts with several modal views presented above `NoKeySetView`. From the other hand the onboarding flow always calls the `onKeySetAddCompletion` once keys are added. Thus one can fully rely on the completion closure for onboarding to update the state once flow is fully dismissed. Updating the view hierarchy based on SeedMediator subscription still needed for some cases in the `keyDetails` state such as wipe.
The PR also fixes the build issue with XCode 16.3 that removes TARGET_OS_* support

fix: banana split onboarding

---

ios/PolkadotVault/Core/Database/DatabaseMediator.swift
ios/PolkadotVaultTests/StateMediators/DatabaseMediatorTests.swift

The PR introduces a fix to App Store migration. Since the is migrated to Novasama Technologies App Store the previous keychain/seeds will not be available to a user. However, the old database file still available to the application that introduces inconsistencies with the new keychain data. The solution is to change database filename and thus triggering database recreation after the migrated update is installed above old app version.

fix: migration app store

---

android/src/main/java/io/parity/signer/screens/keysets/restore/KeysetRecoverViewModel.kt

Current logic always maintains `SPACE_CHARACTER` at the beginning of the unfinished word user input. When it sees that this character is missing, it assumes user wants to delete the previous word. 
However, when checking whether the current input is a full word, the logic checks that `rawUserInput.endsWith(KeysetRecoverModel.SPACE_CHARACTER)` which false-positevely triggers when the input is just `SPACE_CHARACTER`. So, the fix is to check for the length of the input in addition to the current check
Overall this logic should be refactored since it is hard to understand 3 level of nested if statements

fix: cannot remove unfinished word content

---

rust/transaction_parsing/src/derivations.rs
rust/transaction_parsing/src/tests.rs

Current logic for derivations import don't allow to import the same derivation for a network if it exists for another network. The PR relaxes the constraint allowing the aforementioned use case possible.
Closes #2494

feat: allow importing same derivation for another chain

---

.spellcheck/signer.dic
README.md
rust/constants/src/test_values.rs
rust/db_handling/src/cold_default.rs
rust/db_handling/src/identities.rs
rust/db_handling/src/interface_signer.rs
rust/defaults/src/lib.rs
rust/definitions/src/derivations.rs
rust/definitions/src/helpers.rs
rust/generate_message/src/helpers.rs
rust/navigator/src/lib.rs
rust/navigator/src/tests.rs
rust/transaction_parsing/src/cards.rs
rust/transaction_parsing/src/derivations.rs
rust/transaction_parsing/src/message.rs
rust/transaction_parsing/src/parse_transaction.rs

Current logic of the `base58_or_eth_to_multisigner` assumes that the address provided can be converted back to the public key. That causes the issue since ecdsa addresses can't be converted back to the public key making impossible to import back exported derivations.
The PR fixes the issue in the following way:
- `print_multisigner_as_base58_or_eth` is renamed to the `print_multisigner_as_base58_or_eth_address` and is used solely to get address to display from a public key
- New `print_multisigner_as_base58_or_eth_public_key` function is introduced to use for the export of the derivations inside keysets. 
- `base58_or_eth_to_multisigner` is renamed to `base58_or_eth_pubkey_to_multisigner` and now assumes that ecdsa is represented by the hex of the public key
Fixes #2490

fix: export and import of the derivations
